(X86Program
  ((Def
     (Label main)
     (Finfo2
       (conflicts
         (((VarL $ea.1)
           ((VarL $tmp.4)
            (VarL _.1)
            (VarL _.2)
            (VarL _.3)
            (VarL _.4)
            (VarL _.5)
            (RegL Rsp)
            (RegL Rcx)
            (RegL Rdx)
            (RegL Rsi)
            (RegL Rdi)
            (RegL R8)
            (RegL R11)
            (RegL R15)))
          ((VarL $ea.2)
           ((VarL $tmp.8)
            (VarL _.7)
            (VarL _.8)
            (VarL _.9)
            (VarL a.1)
            (RegL Rsp)
            (RegL Rcx)
            (RegL Rdx)
            (RegL Rsi)
            (RegL Rdi)
            (RegL R8)
            (RegL R11)))
          ((VarL $tmp.1)
           ((VarL $tmp.4) (RegL Rsp) (RegL R15)))
          ((VarL $tmp.2)
           ((VarL $tmp.3)
            (VarL $tmp.4)
            (RegL Rsp)
            (RegL R15)))
          ((VarL $tmp.3)
           ((VarL $tmp.2)
            (VarL $tmp.4)
            (RegL Rsp)
            (RegL R15)))
          ((VarL $tmp.4)
           ((VarL $ea.1)
            (VarL $tmp.1)
            (VarL $tmp.2)
            (VarL $tmp.3)
            (VarL _.1)
            (VarL _.2)
            (VarL _.3)
            (VarL _.4)
            (VarL _.5)
            (VarL _.6)
            (RegL Rsp)
            (RegL Rax)
            (RegL Rcx)
            (RegL Rdx)
            (RegL Rsi)
            (RegL Rdi)
            (RegL R8)
            (RegL R9)
            (RegL R10)
            (RegL R11)
            (RegL R15)
            (RegL Rflags)))
          ((VarL $tmp.5)
           ((VarL $tmp.8)
            (VarL a.1)
            (RegL Rsp)
            (RegL R15)))
          ((VarL $tmp.6)
           ((VarL $tmp.7)
            (VarL $tmp.8)
            (VarL a.1)
            (RegL Rsp)
            (RegL R15)))
          ((VarL $tmp.7)
           ((VarL $tmp.6)
            (VarL $tmp.8)
            (VarL a.1)
            (RegL Rsp)
            (RegL R15)))
          ((VarL $tmp.8)
           ((VarL $ea.2)
            (VarL $tmp.5)
            (VarL $tmp.6)
            (VarL $tmp.7)
            (VarL _.10)
            (VarL _.7)
            (VarL _.8)
            (VarL _.9)
            (VarL a.1)
            (RegL Rsp)
            (RegL Rax)
            (RegL Rcx)
            (RegL Rdx)
            (RegL Rsi)
            (RegL Rdi)
            (RegL R8)
            (RegL R9)
            (RegL R10)
            (RegL R11)
            (RegL R15)
            (RegL Rflags)))
          ((VarL _.1)
           ((VarL $ea.1)
            (VarL $tmp.4)
            (RegL Rsp)
            (RegL R15)))
          ((VarL _.10)
           ((VarL $tmp.8) (VarL a.1) (RegL Rsp)))
          ((VarL _.2)
           ((VarL $ea.1)
            (VarL $tmp.4)
            (RegL Rsp)
            (RegL R15)))
          ((VarL _.3)
           ((VarL $ea.1)
            (VarL $tmp.4)
            (RegL Rsp)
            (RegL R15)))
          ((VarL _.4)
           ((VarL $ea.1)
            (VarL $tmp.4)
            (RegL Rsp)
            (RegL R15)))
          ((VarL _.5)
           ((VarL $ea.1)
            (VarL $tmp.4)
            (RegL Rsp)
            (RegL R15)))
          ((VarL _.6)
           ((VarL $tmp.4) (RegL Rsp) (RegL R15)))
          ((VarL _.7)
           ((VarL $ea.2)
            (VarL $tmp.8)
            (VarL a.1)
            (RegL Rsp)))
          ((VarL _.8)
           ((VarL $ea.2)
            (VarL $tmp.8)
            (VarL a.1)
            (RegL Rsp)))
          ((VarL _.9)
           ((VarL $ea.2)
            (VarL $tmp.8)
            (VarL a.1)
            (RegL Rsp)))
          ((VarL a.1)
           ((VarL $ea.2)
            (VarL $tmp.5)
            (VarL $tmp.6)
            (VarL $tmp.7)
            (VarL $tmp.8)
            (VarL _.10)
            (VarL _.7)
            (VarL _.8)
            (VarL _.9)
            (VarL b.1)
            (RegL Rsp)
            (RegL Rax)
            (RegL Rcx)
            (RegL Rdx)
            (RegL Rsi)
            (RegL Rdi)
            (RegL R8)
            (RegL R9)
            (RegL R10)
            (RegL R11)
            (RegL R15)
            (RegL Rflags)))
          ((VarL b.1)
           ((VarL a.1) (RegL Rsp) (RegL Rax)))
          ((VarL big) ((RegL Rsp)))
          ((VarL big2) ((RegL Rsp)))
          ((RegL Rsp)
           ((VarL $ea.1)
            (VarL $ea.2)
            (VarL $tmp.1)
            (VarL $tmp.2)
            (VarL $tmp.3)
            (VarL $tmp.4)
            (VarL $tmp.5)
            (VarL $tmp.6)
            (VarL $tmp.7)
            (VarL $tmp.8)
            (VarL _.1)
            (VarL _.10)
            (VarL _.2)
            (VarL _.3)
            (VarL _.4)
            (VarL _.5)
            (VarL _.6)
            (VarL _.7)
            (VarL _.8)
            (VarL _.9)
            (VarL a.1)
            (VarL b.1)
            (VarL big)
            (VarL big2)
            (RegL Rax)
            (RegL Rcx)
            (RegL Rdx)
            (RegL Rsi)
            (RegL Rdi)
            (RegL R8)
            (RegL R9)
            (RegL R10)
            (RegL R11)
            (RegL Rflags)))
          ((RegL Rax)
           ((VarL $tmp.4)
            (VarL $tmp.8)
            (VarL a.1)
            (VarL b.1)
            (RegL Rsp)
            (RegL Rcx)
            (RegL Rdx)
            (RegL Rsi)
            (RegL Rdi)
            (RegL R8)
            (RegL R9)
            (RegL R10)
            (RegL R11)
            (RegL R15)))
          ((RegL Rcx)
           ((VarL $ea.1)
            (VarL $ea.2)
            (VarL $tmp.4)
            (VarL $tmp.8)
            (VarL a.1)
            (RegL Rsp)
            (RegL Rax)
            (RegL Rdx)
            (RegL Rsi)
            (RegL Rdi)
            (RegL R8)
            (RegL R9)
            (RegL R15)))
          ((RegL Rdx)
           ((VarL $ea.1)
            (VarL $ea.2)
            (VarL $tmp.4)
            (VarL $tmp.8)
            (VarL a.1)
            (RegL Rsp)
            (RegL Rax)
            (RegL Rcx)
            (RegL Rsi)
            (RegL Rdi)
            (RegL R8)
            (RegL R9)
            (RegL R15)))
          ((RegL Rsi)
           ((VarL $ea.1)
            (VarL $ea.2)
            (VarL $tmp.4)
            (VarL $tmp.8)
            (VarL a.1)
            (RegL Rsp)
            (RegL Rax)
            (RegL Rcx)
            (RegL Rdx)
            (RegL Rdi)
            (RegL R8)
            (RegL R9)
            (RegL R15)))
          ((RegL Rdi)
           ((VarL $ea.1)
            (VarL $ea.2)
            (VarL $tmp.4)
            (VarL $tmp.8)
            (VarL a.1)
            (RegL Rsp)
            (RegL Rax)
            (RegL Rcx)
            (RegL Rdx)
            (RegL Rsi)
            (RegL R8)
            (RegL R9)
            (RegL R15)))
          ((RegL R8)
           ((VarL $ea.1)
            (VarL $ea.2)
            (VarL $tmp.4)
            (VarL $tmp.8)
            (VarL a.1)
            (RegL Rsp)
            (RegL Rax)
            (RegL Rcx)
            (RegL Rdx)
            (RegL Rsi)
            (RegL Rdi)
            (RegL R9)
            (RegL R15)))
          ((RegL R9)
           ((VarL $tmp.4)
            (VarL $tmp.8)
            (VarL a.1)
            (RegL Rsp)
            (RegL Rax)
            (RegL Rcx)
            (RegL Rdx)
            (RegL Rsi)
            (RegL Rdi)
            (RegL R8)
            (RegL R15)))
          ((RegL R10)
           ((VarL $tmp.4)
            (VarL $tmp.8)
            (VarL a.1)
            (RegL Rsp)
            (RegL Rax)
            (RegL R15)))
          ((RegL R11)
           ((VarL $ea.1)
            (VarL $ea.2)
            (VarL $tmp.4)
            (VarL $tmp.8)
            (VarL a.1)
            (RegL Rsp)
            (RegL Rax)
            (RegL R15)))
          ((RegL R15)
           ((VarL $ea.1)
            (VarL $tmp.1)
            (VarL $tmp.2)
            (VarL $tmp.3)
            (VarL $tmp.4)
            (VarL $tmp.5)
            (VarL $tmp.6)
            (VarL $tmp.7)
            (VarL $tmp.8)
            (VarL _.1)
            (VarL _.2)
            (VarL _.3)
            (VarL _.4)
            (VarL _.5)
            (VarL _.6)
            (VarL a.1)
            (RegL Rax)
            (RegL Rcx)
            (RegL Rdx)
            (RegL Rsi)
            (RegL Rdi)
            (RegL R8)
            (RegL R9)
            (RegL R10)
            (RegL R11)
            (RegL Rflags)))
          ((RegL Rflags)
           ((VarL $tmp.4)
            (VarL $tmp.8)
            (VarL a.1)
            (RegL Rsp)
            (RegL R15))))))
     ((nparams 0)
      (locals
        (($ea.1
           (Vector
             (Integer
               Integer
               Integer
               Integer
               Integer)))
         ($ea.2
           (Vector (Integer Integer Integer)))
         ($tmp.1 Integer)
         ($tmp.2 Integer)
         ($tmp.3 Integer)
         ($tmp.4
           (Function
             (Integer
               Integer
               Integer
               Integer
               Integer
               (Vector
                 (Integer
                   Integer
                   Integer
                   Integer
                   Integer)))
             Integer))
         ($tmp.5 Integer)
         ($tmp.6 Integer)
         ($tmp.7 Integer)
         ($tmp.8
           (Function
             (Integer
               Integer
               Integer
               Integer
               Integer
               (Vector (Integer Integer Integer)))
             Integer))
         (_.1 Unit)
         (_.10 Unit)
         (_.2 Unit)
         (_.3 Unit)
         (_.4 Unit)
         (_.5 Unit)
         (_.6 Unit)
         (_.7 Unit)
         (_.8 Unit)
         (_.9 Unit)
         (a.1 Integer)
         (b.1 Integer)
         (big
           (Function
             (Integer
               Integer
               Integer
               Integer
               Integer
               (Vector
                 (Integer
                   Integer
                   Integer
                   Integer
                   Integer)))
             Integer))
         (big2
           (Function
             (Integer
               Integer
               Integer
               Integer
               Integer
               (Vector (Integer Integer Integer)))
             Integer))))
      (body
        (((Label block_1)
          (Block
            Binfo1
            ((Movq
               (GlobalArg (Label free_ptr))
               (Reg R11))
             (Addq
               (Imm 32)
               (GlobalArg (Label free_ptr)))
             (Movq (Imm 7) (Deref R11 0))
             (Movq (Reg R11) (Var $ea.2))
             (Movq (Var $ea.2) (Reg R11))
             (Movq (Imm 6) (Deref R11 8))
             (Movq (Imm 0) (Var _.9))
             (Movq (Var $ea.2) (Reg R11))
             (Movq (Imm 7) (Deref R11 16))
             (Movq (Imm 0) (Var _.8))
             (Movq (Var $ea.2) (Reg R11))
             (Movq (Imm 11) (Deref R11 24))
             (Movq (Imm 0) (Var _.7))
             (Movq (Imm 1) (Reg Rdi))
             (Movq (Imm 2) (Reg Rsi))
             (Movq (Imm 3) (Reg Rdx))
             (Movq (Imm 10) (Reg Rcx))
             (Movq (Imm 5) (Reg R8))
             (Movq (Var $ea.2) (Reg R9))
             (IndirectCallq (Var $tmp.8) 6)
             (Movq (Reg Rax) (Var b.1))
             (Movq (Var a.1) (Reg Rax))
             (Addq (Var b.1) (Reg Rax))
             (Jmp (Label main_conclusion)))))
         ((Label block_2)
          (Block
            Binfo1
            ((Movq (Imm 0) (Var _.10))
             (Jmp (Label block_1)))))
         ((Label block_3)
          (Block
            Binfo1
            ((Movq (Reg R15) (Reg Rdi))
             (Movq (Imm 32) (Reg Rsi))
             (Callq (Label collect) 2)
             (Jmp (Label block_1)))))
         ((Label block_4)
          (Block
            Binfo1
            ((Movq
               (GlobalArg (Label free_ptr))
               (Reg R11))
             (Addq
               (Imm 48)
               (GlobalArg (Label free_ptr)))
             (Movq (Imm 11) (Deref R11 0))
             (Movq (Reg R11) (Var $ea.1))
             (Movq (Var $ea.1) (Reg R11))
             (Movq (Imm 6) (Deref R11 8))
             (Movq (Imm 0) (Var _.5))
             (Movq (Var $ea.1) (Reg R11))
             (Movq (Imm 7) (Deref R11 16))
             (Movq (Imm 0) (Var _.4))
             (Movq (Var $ea.1) (Reg R11))
             (Movq (Imm 8) (Deref R11 24))
             (Movq (Imm 0) (Var _.3))
             (Movq (Var $ea.1) (Reg R11))
             (Movq (Imm 9) (Deref R11 32))
             (Movq (Imm 0) (Var _.2))
             (Movq (Var $ea.1) (Reg R11))
             (Movq (Imm 11) (Deref R11 40))
             (Movq (Imm 0) (Var _.1))
             (Movq (Imm 1) (Reg Rdi))
             (Movq (Imm 2) (Reg Rsi))
             (Movq (Imm 3) (Reg Rdx))
             (Movq (Imm 10) (Reg Rcx))
             (Movq (Imm 5) (Reg R8))
             (Movq (Var $ea.1) (Reg R9))
             (IndirectCallq (Var $tmp.4) 6)
             (Movq (Reg Rax) (Var a.1))
             (Leaq
               (GlobalArg (Label big2))
               (Var $tmp.8))
             (Movq
               (GlobalArg (Label free_ptr))
               (Var $tmp.5))
             (Movq (Var $tmp.5) (Var $tmp.6))
             (Addq (Imm 32) (Var $tmp.6))
             (Movq
               (GlobalArg (Label fromspace_end))
               (Var $tmp.7))
             (Cmpq (Var $tmp.7) (Var $tmp.6))
             (JmpIf CC_l (Label block_2))
             (Jmp (Label block_3)))))
         ((Label block_5)
          (Block
            Binfo1
            ((Movq (Imm 0) (Var _.6))
             (Jmp (Label block_4)))))
         ((Label block_6)
          (Block
            Binfo1
            ((Movq (Reg R15) (Reg Rdi))
             (Movq (Imm 48) (Reg Rsi))
             (Callq (Label collect) 2)
             (Jmp (Label block_4)))))
         ((Label main_start)
          (Block
            Binfo1
            ((Leaq
               (GlobalArg (Label big))
               (Var $tmp.4))
             (Movq
               (GlobalArg (Label free_ptr))
               (Var $tmp.1))
             (Movq (Var $tmp.1) (Var $tmp.2))
             (Addq (Imm 48) (Var $tmp.2))
             (Movq
               (GlobalArg (Label fromspace_end))
               (Var $tmp.3))
             (Cmpq (Var $tmp.3) (Var $tmp.2))
             (JmpIf CC_l (Label block_5))
             (Jmp (Label block_6)))))))))
   (Def
     (Label big)
     (Finfo2
       (conflicts
         (((VarL $tmp.9)
           ((VarL d.1) (RegL Rsp) (RegL Rax)))
          ((VarL $tup.1) ((VarL d.1) (RegL Rsp)))
          ((VarL a.2)
           ((RegL Rsp)
            (RegL Rcx)
            (RegL Rdx)
            (RegL Rsi)
            (RegL R8)
            (RegL R9)))
          ((VarL b.2)
           ((RegL Rsp)
            (RegL Rcx)
            (RegL Rdx)
            (RegL R8)
            (RegL R9)))
          ((VarL c.1)
           ((RegL Rsp)
            (RegL Rcx)
            (RegL R8)
            (RegL R9)))
          ((VarL d.1)
           ((VarL $tmp.9)
            (VarL $tup.1)
            (VarL e.1)
            (RegL Rsp)
            (RegL R8)
            (RegL R9)
            (RegL R11)))
          ((VarL e.1)
           ((VarL d.1) (RegL Rsp) (RegL R9)))
          ((RegL Rsp)
           ((VarL $tmp.9)
            (VarL $tup.1)
            (VarL a.2)
            (VarL b.2)
            (VarL c.1)
            (VarL d.1)
            (VarL e.1)
            (RegL Rax)
            (RegL R11)))
          ((RegL Rax) ((VarL $tmp.9) (RegL Rsp)))
          ((RegL Rcx)
           ((VarL a.2) (VarL b.2) (VarL c.1)))
          ((RegL Rdx) ((VarL a.2) (VarL b.2)))
          ((RegL Rsi) ((VarL a.2)))
          ((RegL R8)
           ((VarL a.2)
            (VarL b.2)
            (VarL c.1)
            (VarL d.1)))
          ((RegL R9)
           ((VarL a.2)
            (VarL b.2)
            (VarL c.1)
            (VarL d.1)
            (VarL e.1)))
          ((RegL R11) ((VarL d.1) (RegL Rsp))))))
     ((nparams 6)
      (locals
        ((a.2 Integer)
         (b.2 Integer)
         (c.1 Integer)
         (d.1 Integer)
         (e.1 Integer)
         ($tup.1
           (Vector
             (Integer
               Integer
               Integer
               Integer
               Integer)))
         ($tmp.9 Integer)
         ($tup.1
           (Vector
             (Integer
               Integer
               Integer
               Integer
               Integer)))
         (d.1 Integer)))
      (body
        (((Label big_start)
          (Block
            Binfo1
            ((Movq (Reg Rdi) (Var a.2))
             (Movq (Reg Rsi) (Var b.2))
             (Movq (Reg Rdx) (Var c.1))
             (Movq (Reg Rcx) (Var d.1))
             (Movq (Reg R8) (Var e.1))
             (Movq (Reg R9) (Var $tup.1))
             (Movq (Var $tup.1) (Reg R11))
             (Movq (Deref R11 40) (Var $tmp.9))
             (Movq (Var d.1) (Reg Rax))
             (Addq (Var $tmp.9) (Reg Rax))
             (Jmp (Label big_conclusion)))))))))
   (Def
     (Label big2)
     (Finfo2
       (conflicts
         (((VarL $tmp.10)
           ((VarL d.2) (RegL Rsp) (RegL Rax)))
          ((VarL $tup.2) ((VarL d.2) (RegL Rsp)))
          ((VarL a.3)
           ((RegL Rsp)
            (RegL Rcx)
            (RegL Rdx)
            (RegL Rsi)
            (RegL R8)
            (RegL R9)))
          ((VarL b.3)
           ((RegL Rsp)
            (RegL Rcx)
            (RegL Rdx)
            (RegL R8)
            (RegL R9)))
          ((VarL c.2)
           ((RegL Rsp)
            (RegL Rcx)
            (RegL R8)
            (RegL R9)))
          ((VarL d.2)
           ((VarL $tmp.10)
            (VarL $tup.2)
            (VarL e.2)
            (RegL Rsp)
            (RegL R8)
            (RegL R9)
            (RegL R11)))
          ((VarL e.2)
           ((VarL d.2) (RegL Rsp) (RegL R9)))
          ((RegL Rsp)
           ((VarL $tmp.10)
            (VarL $tup.2)
            (VarL a.3)
            (VarL b.3)
            (VarL c.2)
            (VarL d.2)
            (VarL e.2)
            (RegL Rax)
            (RegL R11)))
          ((RegL Rax) ((VarL $tmp.10) (RegL Rsp)))
          ((RegL Rcx)
           ((VarL a.3) (VarL b.3) (VarL c.2)))
          ((RegL Rdx) ((VarL a.3) (VarL b.3)))
          ((RegL Rsi) ((VarL a.3)))
          ((RegL R8)
           ((VarL a.3)
            (VarL b.3)
            (VarL c.2)
            (VarL d.2)))
          ((RegL R9)
           ((VarL a.3)
            (VarL b.3)
            (VarL c.2)
            (VarL d.2)
            (VarL e.2)))
          ((RegL R11) ((VarL d.2) (RegL Rsp))))))
     ((nparams 6)
      (locals
        ((a.3 Integer)
         (b.3 Integer)
         (c.2 Integer)
         (d.2 Integer)
         (e.2 Integer)
         ($tup.2
           (Vector (Integer Integer Integer)))
         ($tmp.10 Integer)
         ($tup.2
           (Vector (Integer Integer Integer)))
         (d.2 Integer)))
      (body
        (((Label big2_start)
          (Block
            Binfo1
            ((Movq (Reg Rdi) (Var a.3))
             (Movq (Reg Rsi) (Var b.3))
             (Movq (Reg Rdx) (Var c.2))
             (Movq (Reg Rcx) (Var d.2))
             (Movq (Reg R8) (Var e.2))
             (Movq (Reg R9) (Var $tup.2))
             (Movq (Var $tup.2) (Reg R11))
             (Movq (Deref R11 24) (Var $tmp.10))
             (Movq (Var d.2) (Reg Rax))
             (Addq (Var $tmp.10) (Reg Rax))
             (Jmp (Label big2_conclusion)))))))))))
