(X86Program
  ((Def
     (Label main)
     (Finfo2
       (conflicts
         (((VarL $ea.1)
           ((VarL _.1)
            (VarL _.2)
            (VarL _.3)
            (RegL Rsp)
            (RegL R11)))
          ((VarL $tmp.1) ((RegL Rsp) (RegL R15)))
          ((VarL $tmp.10)
           ((VarL $tmp.6)
            (VarL $tmp.9)
            (RegL Rsp)
            (RegL Rax)))
          ((VarL $tmp.2)
           ((VarL $tmp.3) (RegL Rsp) (RegL R15)))
          ((VarL $tmp.3)
           ((VarL $tmp.2) (RegL Rsp) (RegL R15)))
          ((VarL $tmp.4)
           ((VarL $tmp.5) (VarL vec.1) (RegL Rsp)))
          ((VarL $tmp.5)
           ((VarL $tmp.4)
            (VarL vec.1)
            (RegL Rsp)
            (RegL Rsi)
            (RegL Rdi)))
          ((VarL $tmp.6)
           ((VarL $tmp.10)
            (VarL $tmp.7)
            (VarL $tmp.8)
            (VarL $tmp.9)
            (VarL vec2.1)
            (RegL Rsp)
            (RegL R11)))
          ((VarL $tmp.7)
           ((VarL $tmp.6)
            (VarL $tmp.8)
            (VarL $tmp.9)
            (VarL vec2.1)
            (RegL Rsp)
            (RegL R11)))
          ((VarL $tmp.8)
           ((VarL $tmp.6) (VarL $tmp.7) (RegL Rsp)))
          ((VarL $tmp.9)
           ((VarL $tmp.10)
            (VarL $tmp.6)
            (VarL $tmp.7)
            (RegL Rsp)))
          ((VarL _.1) ((VarL $ea.1) (RegL Rsp)))
          ((VarL _.2) ((VarL $ea.1) (RegL Rsp)))
          ((VarL _.3) ((VarL $ea.1) (RegL Rsp)))
          ((VarL _.4) ((RegL Rsp)))
          ((VarL add1) ((RegL Rsp)))
          ((VarL mapint) ((RegL Rsp)))
          ((VarL vec.1)
           ((VarL $tmp.4)
            (VarL $tmp.5)
            (RegL Rsp)
            (RegL Rdi)))
          ((VarL vec2.1)
           ((VarL $tmp.6) (VarL $tmp.7) (RegL Rsp)))
          ((RegL Rsp)
           ((VarL $ea.1)
            (VarL $tmp.1)
            (VarL $tmp.10)
            (VarL $tmp.2)
            (VarL $tmp.3)
            (VarL $tmp.4)
            (VarL $tmp.5)
            (VarL $tmp.6)
            (VarL $tmp.7)
            (VarL $tmp.8)
            (VarL $tmp.9)
            (VarL _.1)
            (VarL _.2)
            (VarL _.3)
            (VarL _.4)
            (VarL add1)
            (VarL mapint)
            (VarL vec.1)
            (VarL vec2.1)
            (RegL Rax)
            (RegL Rcx)
            (RegL Rdx)
            (RegL Rsi)
            (RegL Rdi)
            (RegL R8)
            (RegL R9)
            (RegL R10)
            (RegL R11)
            (RegL Rflags)))
          ((RegL Rax)
           ((VarL $tmp.10)
            (RegL Rsp)
            (RegL Rcx)
            (RegL Rdx)
            (RegL Rsi)
            (RegL Rdi)
            (RegL R8)
            (RegL R9)
            (RegL R10)
            (RegL R11)))
          ((RegL Rcx) ((RegL Rsp) (RegL Rax)))
          ((RegL Rdx) ((RegL Rsp) (RegL Rax)))
          ((RegL Rsi)
           ((VarL $tmp.5)
            (RegL Rsp)
            (RegL Rax)
            (RegL Rdi)))
          ((RegL Rdi)
           ((VarL $tmp.5)
            (VarL vec.1)
            (RegL Rsp)
            (RegL Rax)
            (RegL Rsi)))
          ((RegL R8) ((RegL Rsp) (RegL Rax)))
          ((RegL R9) ((RegL Rsp) (RegL Rax)))
          ((RegL R10) ((RegL Rsp) (RegL Rax)))
          ((RegL R11)
           ((VarL $ea.1)
            (VarL $tmp.6)
            (VarL $tmp.7)
            (RegL Rsp)
            (RegL Rax)))
          ((RegL R15)
           ((VarL $tmp.1)
            (VarL $tmp.2)
            (VarL $tmp.3)
            (RegL Rflags)))
          ((RegL Rflags) ((RegL Rsp) (RegL R15))))))
     ((nparams 0)
      (locals
        (($ea.1
           (Vector (Integer Integer Integer)))
         ($tmp.1 Integer)
         ($tmp.10 Integer)
         ($tmp.2 Integer)
         ($tmp.3 Integer)
         ($tmp.4 (Function (Integer) Integer))
         ($tmp.5
           (Function
             ((Function (Integer) Integer)
              (Vector (Integer Integer Integer)))
             (Vector (Integer Integer Integer))))
         ($tmp.6 Integer)
         ($tmp.7 Integer)
         ($tmp.8 Integer)
         ($tmp.9 Integer)
         (_.1 Unit)
         (_.2 Unit)
         (_.3 Unit)
         (_.4 Unit)
         (add1 (Function (Integer) Integer))
         (mapint
           (Function
             ((Function (Integer) Integer)
              (Vector (Integer Integer Integer)))
             (Vector (Integer Integer Integer))))
         (vec.1
           (Vector (Integer Integer Integer)))
         (vec2.1
           (Vector (Integer Integer Integer)))))
      (body
        (((Label block_1)
          (Block
            Binfo1
            ((Movq
               (GlobalArg (Label free_ptr))
               (Reg R11))
             (Addq
               (Imm 32)
               (GlobalArg (Label free_ptr)))
             (Movq (Imm 7) (Deref R11 0))
             (Movq (Reg R11) (Var $ea.1))
             (Movq (Var $ea.1) (Reg R11))
             (Movq (Imm 1) (Deref R11 8))
             (Movq (Imm 0) (Var _.3))
             (Movq (Var $ea.1) (Reg R11))
             (Movq (Imm 2) (Deref R11 16))
             (Movq (Imm 0) (Var _.2))
             (Movq (Var $ea.1) (Reg R11))
             (Movq (Imm 3) (Deref R11 24))
             (Movq (Imm 0) (Var _.1))
             (Movq (Var $ea.1) (Var vec.1))
             (Leaq
               (GlobalArg (Label mapint))
               (Var $tmp.5))
             (Leaq
               (GlobalArg (Label add1))
               (Var $tmp.4))
             (Movq (Var $tmp.4) (Reg Rdi))
             (Movq (Var vec.1) (Reg Rsi))
             (IndirectCallq (Var $tmp.5) 2)
             (Movq (Reg Rax) (Var vec2.1))
             (Movq (Var vec2.1) (Reg R11))
             (Movq (Deref R11 8) (Var $tmp.6))
             (Movq (Var vec2.1) (Reg R11))
             (Movq (Deref R11 16) (Var $tmp.7))
             (Movq (Var vec2.1) (Reg R11))
             (Movq (Deref R11 24) (Var $tmp.8))
             (Movq (Var $tmp.8) (Var $tmp.9))
             (Addq (Imm 33) (Var $tmp.9))
             (Movq (Var $tmp.7) (Var $tmp.10))
             (Addq (Var $tmp.9) (Var $tmp.10))
             (Movq (Var $tmp.6) (Reg Rax))
             (Addq (Var $tmp.10) (Reg Rax))
             (Jmp (Label main_conclusion)))))
         ((Label block_2)
          (Block
            Binfo1
            ((Movq (Imm 0) (Var _.4))
             (Jmp (Label block_1)))))
         ((Label block_3)
          (Block
            Binfo1
            ((Movq (Reg R15) (Reg Rdi))
             (Movq (Imm 32) (Reg Rsi))
             (Callq (Label collect) 2)
             (Jmp (Label block_1)))))
         ((Label main_start)
          (Block
            Binfo1
            ((Movq
               (GlobalArg (Label free_ptr))
               (Var $tmp.1))
             (Movq (Var $tmp.1) (Var $tmp.2))
             (Addq (Imm 32) (Var $tmp.2))
             (Movq
               (GlobalArg (Label fromspace_end))
               (Var $tmp.3))
             (Cmpq (Var $tmp.3) (Var $tmp.2))
             (JmpIf CC_l (Label block_2))
             (Jmp (Label block_3)))))))))
   (Def
     (Label mapint)
     (Finfo2
       (conflicts
         (((VarL $ea.2)
           ((VarL $ea.3)
            (VarL $ea.4)
            (VarL $ea.5)
            (VarL $tmp.12)
            (VarL $tmp.13)
            (VarL $tmp.14)
            (VarL $tmp.15)
            (VarL $tmp.16)
            (VarL _.8)
            (VarL fun.1)
            (VarL v.1)
            (RegL Rsp)
            (RegL Rax)
            (RegL Rcx)
            (RegL Rdx)
            (RegL Rsi)
            (RegL Rdi)
            (RegL R8)
            (RegL R9)
            (RegL R10)
            (RegL R11)
            (RegL R15)
            (RegL Rflags)))
          ((VarL $ea.3)
           ((VarL $ea.2)
            (VarL $ea.4)
            (VarL $ea.5)
            (VarL $tmp.13)
            (VarL $tmp.14)
            (VarL $tmp.15)
            (VarL $tmp.16)
            (VarL _.7)
            (VarL _.8)
            (VarL fun.1)
            (VarL v.1)
            (RegL Rsp)
            (RegL Rax)
            (RegL Rcx)
            (RegL Rdx)
            (RegL Rsi)
            (RegL Rdi)
            (RegL R8)
            (RegL R9)
            (RegL R10)
            (RegL R11)
            (RegL R15)
            (RegL Rflags)))
          ((VarL $ea.4)
           ((VarL $ea.2)
            (VarL $ea.3)
            (VarL $ea.5)
            (VarL $tmp.14)
            (VarL $tmp.15)
            (VarL $tmp.16)
            (VarL _.6)
            (VarL _.7)
            (VarL _.8)
            (RegL Rsp)
            (RegL Rax)
            (RegL Rcx)
            (RegL Rdx)
            (RegL Rsi)
            (RegL Rdi)
            (RegL R8)
            (RegL R9)
            (RegL R10)
            (RegL R11)
            (RegL R15)
            (RegL Rflags)))
          ((VarL $ea.5)
           ((VarL $ea.2)
            (VarL $ea.3)
            (VarL $ea.4)
            (VarL _.5)
            (VarL _.6)
            (VarL _.7)
            (RegL Rsp)
            (RegL R11)))
          ((VarL $tmp.11)
           ((VarL fun.1)
            (VarL v.1)
            (RegL Rsp)
            (RegL R15)))
          ((VarL $tmp.12)
           ((VarL $ea.2)
            (VarL fun.1)
            (VarL v.1)
            (RegL Rsp)
            (RegL R15)))
          ((VarL $tmp.13)
           ((VarL $ea.2)
            (VarL $ea.3)
            (VarL fun.1)
            (RegL Rsp)
            (RegL R15)))
          ((VarL $tmp.14)
           ((VarL $ea.2)
            (VarL $ea.3)
            (VarL $ea.4)
            (RegL Rsp)
            (RegL R15)))
          ((VarL $tmp.15)
           ((VarL $ea.2)
            (VarL $ea.3)
            (VarL $ea.4)
            (VarL $tmp.16)
            (RegL Rsp)
            (RegL R15)))
          ((VarL $tmp.16)
           ((VarL $ea.2)
            (VarL $ea.3)
            (VarL $ea.4)
            (VarL $tmp.15)
            (RegL Rsp)
            (RegL R15)))
          ((VarL _.5) ((VarL $ea.5) (RegL Rsp)))
          ((VarL _.6)
           ((VarL $ea.4) (VarL $ea.5) (RegL Rsp)))
          ((VarL _.7)
           ((VarL $ea.3)
            (VarL $ea.4)
            (VarL $ea.5)
            (RegL Rsp)))
          ((VarL _.8)
           ((VarL $ea.2)
            (VarL $ea.3)
            (VarL $ea.4)
            (RegL Rsp)))
          ((VarL fun.1)
           ((VarL $ea.2)
            (VarL $ea.3)
            (VarL $tmp.11)
            (VarL $tmp.12)
            (VarL $tmp.13)
            (VarL v.1)
            (RegL Rsp)
            (RegL Rax)
            (RegL Rcx)
            (RegL Rdx)
            (RegL Rsi)
            (RegL Rdi)
            (RegL R8)
            (RegL R9)
            (RegL R10)
            (RegL R11)
            (RegL R15)))
          ((VarL v.1)
           ((VarL $ea.2)
            (VarL $ea.3)
            (VarL $tmp.11)
            (VarL $tmp.12)
            (VarL fun.1)
            (RegL Rsp)
            (RegL Rax)
            (RegL Rbx)
            (RegL Rcx)
            (RegL Rdx)
            (RegL Rsi)
            (RegL Rdi)
            (RegL R8)
            (RegL R9)
            (RegL R10)
            (RegL R11)
            (RegL R12)
            (RegL R13)
            (RegL R14)
            (RegL R15)))
          ((RegL Rsp)
           ((VarL $ea.2)
            (VarL $ea.3)
            (VarL $ea.4)
            (VarL $ea.5)
            (VarL $tmp.11)
            (VarL $tmp.12)
            (VarL $tmp.13)
            (VarL $tmp.14)
            (VarL $tmp.15)
            (VarL $tmp.16)
            (VarL _.5)
            (VarL _.6)
            (VarL _.7)
            (VarL _.8)
            (VarL fun.1)
            (VarL v.1)
            (RegL Rax)
            (RegL Rcx)
            (RegL Rdx)
            (RegL Rsi)
            (RegL Rdi)
            (RegL R8)
            (RegL R9)
            (RegL R10)
            (RegL R11)
            (RegL Rflags)))
          ((RegL Rax)
           ((VarL $ea.2)
            (VarL $ea.3)
            (VarL $ea.4)
            (VarL fun.1)
            (VarL v.1)
            (RegL Rsp)
            (RegL Rcx)
            (RegL Rdx)
            (RegL Rsi)
            (RegL Rdi)
            (RegL R8)
            (RegL R9)
            (RegL R10)
            (RegL R11)
            (RegL R15)))
          ((RegL Rbx) ((VarL v.1)))
          ((RegL Rcx)
           ((VarL $ea.2)
            (VarL $ea.3)
            (VarL $ea.4)
            (VarL fun.1)
            (VarL v.1)
            (RegL Rsp)
            (RegL Rax)
            (RegL R15)))
          ((RegL Rdx)
           ((VarL $ea.2)
            (VarL $ea.3)
            (VarL $ea.4)
            (VarL fun.1)
            (VarL v.1)
            (RegL Rsp)
            (RegL Rax)
            (RegL R15)))
          ((RegL Rsi)
           ((VarL $ea.2)
            (VarL $ea.3)
            (VarL $ea.4)
            (VarL fun.1)
            (VarL v.1)
            (RegL Rsp)
            (RegL Rax)
            (RegL Rdi)
            (RegL R15)))
          ((RegL Rdi)
           ((VarL $ea.2)
            (VarL $ea.3)
            (VarL $ea.4)
            (VarL fun.1)
            (VarL v.1)
            (RegL Rsp)
            (RegL Rax)
            (RegL Rsi)
            (RegL R15)))
          ((RegL R8)
           ((VarL $ea.2)
            (VarL $ea.3)
            (VarL $ea.4)
            (VarL fun.1)
            (VarL v.1)
            (RegL Rsp)
            (RegL Rax)
            (RegL R15)))
          ((RegL R9)
           ((VarL $ea.2)
            (VarL $ea.3)
            (VarL $ea.4)
            (VarL fun.1)
            (VarL v.1)
            (RegL Rsp)
            (RegL Rax)
            (RegL R15)))
          ((RegL R10)
           ((VarL $ea.2)
            (VarL $ea.3)
            (VarL $ea.4)
            (VarL fun.1)
            (VarL v.1)
            (RegL Rsp)
            (RegL Rax)
            (RegL R15)))
          ((RegL R11)
           ((VarL $ea.2)
            (VarL $ea.3)
            (VarL $ea.4)
            (VarL $ea.5)
            (VarL fun.1)
            (VarL v.1)
            (RegL Rsp)
            (RegL Rax)
            (RegL R15)))
          ((RegL R12) ((VarL v.1)))
          ((RegL R13) ((VarL v.1)))
          ((RegL R14) ((VarL v.1)))
          ((RegL R15)
           ((VarL $ea.2)
            (VarL $ea.3)
            (VarL $ea.4)
            (VarL $tmp.11)
            (VarL $tmp.12)
            (VarL $tmp.13)
            (VarL $tmp.14)
            (VarL $tmp.15)
            (VarL $tmp.16)
            (VarL fun.1)
            (VarL v.1)
            (RegL Rax)
            (RegL Rcx)
            (RegL Rdx)
            (RegL Rsi)
            (RegL Rdi)
            (RegL R8)
            (RegL R9)
            (RegL R10)
            (RegL R11)
            (RegL Rflags)))
          ((RegL Rflags)
           ((VarL $ea.2)
            (VarL $ea.3)
            (VarL $ea.4)
            (RegL Rsp)
            (RegL R15))))))
     ((nparams 2)
      (locals
        ((fun.1 (Function (Integer) Integer))
         (v.1 (Vector (Integer Integer Integer)))
         ($ea.2 Integer)
         ($ea.3 Integer)
         ($ea.4 Integer)
         ($ea.5
           (Vector (Integer Integer Integer)))
         ($tmp.11 Integer)
         ($tmp.12 Integer)
         ($tmp.13 Integer)
         ($tmp.14 Integer)
         ($tmp.15 Integer)
         ($tmp.16 Integer)
         (_.5 Unit)
         (_.6 Unit)
         (_.7 Unit)
         (_.8 Unit)
         (fun.1 (Function (Integer) Integer))
         (v.1 (Vector (Integer Integer Integer)))))
      (body
        (((Label block_4)
          (Block
            Binfo1
            ((Movq
               (GlobalArg (Label free_ptr))
               (Reg R11))
             (Addq
               (Imm 32)
               (GlobalArg (Label free_ptr)))
             (Movq (Imm 7) (Deref R11 0))
             (Movq (Reg R11) (Var $ea.5))
             (Movq (Var $ea.5) (Reg R11))
             (Movq (Var $ea.2) (Deref R11 8))
             (Movq (Imm 0) (Var _.7))
             (Movq (Var $ea.5) (Reg R11))
             (Movq (Var $ea.3) (Deref R11 16))
             (Movq (Imm 0) (Var _.6))
             (Movq (Var $ea.5) (Reg R11))
             (Movq (Var $ea.4) (Deref R11 24))
             (Movq (Imm 0) (Var _.5))
             (Movq (Var $ea.5) (Reg Rax))
             (Jmp (Label mapint_conclusion)))))
         ((Label block_5)
          (Block
            Binfo1
            ((Movq (Imm 0) (Var _.8))
             (Jmp (Label block_4)))))
         ((Label block_6)
          (Block
            Binfo1
            ((Movq (Reg R15) (Reg Rdi))
             (Movq (Imm 32) (Reg Rsi))
             (Callq (Label collect) 2)
             (Jmp (Label block_4)))))
         ((Label mapint_start)
          (Block
            Binfo1
            ((Movq (Reg Rdi) (Var fun.1))
             (Movq (Reg Rsi) (Var v.1))
             (Movq (Var v.1) (Reg R11))
             (Movq (Deref R11 8) (Var $tmp.11))
             (Movq (Var $tmp.11) (Reg Rdi))
             (IndirectCallq (Var fun.1) 1)
             (Movq (Reg Rax) (Var $ea.2))
             (Movq (Var v.1) (Reg R11))
             (Movq (Deref R11 16) (Var $tmp.12))
             (Movq (Var $tmp.12) (Reg Rdi))
             (IndirectCallq (Var fun.1) 1)
             (Movq (Reg Rax) (Var $ea.3))
             (Movq (Var v.1) (Reg R11))
             (Movq (Deref R11 24) (Var $tmp.13))
             (Movq (Var $tmp.13) (Reg Rdi))
             (IndirectCallq (Var fun.1) 1)
             (Movq (Reg Rax) (Var $ea.4))
             (Movq
               (GlobalArg (Label free_ptr))
               (Var $tmp.14))
             (Movq (Var $tmp.14) (Var $tmp.15))
             (Addq (Imm 32) (Var $tmp.15))
             (Movq
               (GlobalArg (Label fromspace_end))
               (Var $tmp.16))
             (Cmpq (Var $tmp.16) (Var $tmp.15))
             (JmpIf CC_l (Label block_5))
             (Jmp (Label block_6)))))))))
   (Def
     (Label add1)
     (Finfo2
       (conflicts
         (((VarL x.1) ((RegL Rsp)))
          ((RegL Rsp) ((VarL x.1) (RegL Rax)))
          ((RegL Rax) ((RegL Rsp))))))
     ((nparams 1)
      (locals ((x.1 Integer) (x.1 Integer)))
      (body
        (((Label add1_start)
          (Block
            Binfo1
            ((Movq (Reg Rdi) (Var x.1))
             (Movq (Var x.1) (Reg Rax))
             (Addq (Imm 1) (Reg Rax))
             (Jmp (Label add1_conclusion)))))))))))
