(X86Program
  ((Def
     (Label main)
     (Finfo2
       (conflicts
         (((VarL $tmp.1) ((RegL Rsi) (RegL Rdi)))
          ((VarL mult) ((RegL Rsp)))
          ((RegL Rsp) ((VarL mult)))
          ((RegL Rsi) ((VarL $tmp.1) (RegL Rdi)))
          ((RegL Rdi) ((VarL $tmp.1) (RegL Rsi))))))
     ((nparams 0)
      (locals
        (($tmp.1
           (Function (Integer Integer) Integer))
         (mult
           (Function (Integer Integer) Integer))))
      (body
        (((Label main_start)
          (Block
            Binfo1
            ((Leaq
               (GlobalArg (Label mult))
               (Var $tmp.1))
             (Movq (Imm 6) (Reg Rdi))
             (Movq (Imm 7) (Reg Rsi))
             (TailJmp (Var $tmp.1) 2))))))))
   (Def
     (Label mult)
     (Finfo2
       (conflicts
         (((VarL $tmp.2)
           ((VarL $tmp.4)
            (VarL x.1)
            (VarL y.1)
            (RegL Rsp)))
          ((VarL $tmp.3)
           ((VarL $tmp.4)
            (VarL x.1)
            (VarL y.1)
            (RegL Rsp)))
          ((VarL $tmp.4)
           ((VarL $tmp.2)
            (VarL $tmp.3)
            (VarL x.1)
            (VarL y.1)
            (RegL Rsp)
            (RegL Rsi)
            (RegL Rdi)))
          ((VarL $tmp.5)
           ((VarL y.1) (RegL Rsp) (RegL Rax)))
          ((VarL mult) ((RegL Rsp)))
          ((VarL x.1)
           ((VarL $tmp.2)
            (VarL $tmp.3)
            (VarL $tmp.4)
            (VarL y.1)
            (RegL Rsp)
            (RegL Rsi)
            (RegL Rflags)))
          ((VarL y.1)
           ((VarL $tmp.2)
            (VarL $tmp.3)
            (VarL $tmp.4)
            (VarL $tmp.5)
            (VarL x.1)
            (RegL Rsp)
            (RegL Rax)
            (RegL Rcx)
            (RegL Rdx)
            (RegL Rsi)
            (RegL Rdi)
            (RegL R8)
            (RegL R9)
            (RegL R10)
            (RegL R11)
            (RegL Rflags)))
          ((RegL Rsp)
           ((VarL $tmp.2)
            (VarL $tmp.3)
            (VarL $tmp.4)
            (VarL $tmp.5)
            (VarL mult)
            (VarL x.1)
            (VarL y.1)
            (RegL Rax)
            (RegL Rcx)
            (RegL Rdx)
            (RegL Rsi)
            (RegL Rdi)
            (RegL R8)
            (RegL R9)
            (RegL R10)
            (RegL R11)
            (RegL Rflags)))
          ((RegL Rax)
           ((VarL $tmp.5)
            (VarL y.1)
            (RegL Rsp)
            (RegL Rcx)
            (RegL Rdx)
            (RegL Rsi)
            (RegL Rdi)
            (RegL R8)
            (RegL R9)
            (RegL R10)
            (RegL R11)))
          ((RegL Rcx)
           ((VarL y.1) (RegL Rsp) (RegL Rax)))
          ((RegL Rdx)
           ((VarL y.1) (RegL Rsp) (RegL Rax)))
          ((RegL Rsi)
           ((VarL $tmp.4)
            (VarL x.1)
            (VarL y.1)
            (RegL Rsp)
            (RegL Rax)
            (RegL Rdi)))
          ((RegL Rdi)
           ((VarL $tmp.4)
            (VarL y.1)
            (RegL Rsp)
            (RegL Rax)
            (RegL Rsi)))
          ((RegL R8)
           ((VarL y.1) (RegL Rsp) (RegL Rax)))
          ((RegL R9)
           ((VarL y.1) (RegL Rsp) (RegL Rax)))
          ((RegL R10)
           ((VarL y.1) (RegL Rsp) (RegL Rax)))
          ((RegL R11)
           ((VarL y.1) (RegL Rsp) (RegL Rax)))
          ((RegL Rflags)
           ((VarL x.1) (VarL y.1) (RegL Rsp))))))
     ((nparams 2)
      (locals
        ((x.1 Integer)
         (y.1 Integer)
         ($tmp.2 Integer)
         ($tmp.3 Integer)
         ($tmp.4
           (Function (Integer Integer) Integer))
         ($tmp.5 Integer)
         (mult
           (Function (Integer Integer) Integer))
         (x.1 Integer)
         (y.1 Integer)))
      (body
        (((Label block_1)
          (Block
            Binfo1
            ((Movq (Imm 0) (Reg Rax))
             (Jmp (Label mult_conclusion)))))
         ((Label block_2)
          (Block
            Binfo1
            ((Leaq
               (GlobalArg (Label mult))
               (Var $tmp.4))
             (Movq (Imm 1) (Var $tmp.2))
             (Negq (Var $tmp.2))
             (Movq (Var $tmp.2) (Var $tmp.3))
             (Addq (Var x.1) (Var $tmp.3))
             (Movq (Var $tmp.3) (Reg Rdi))
             (Movq (Var y.1) (Reg Rsi))
             (IndirectCallq (Var $tmp.4) 2)
             (Movq (Reg Rax) (Var $tmp.5))
             (Movq (Var y.1) (Reg Rax))
             (Addq (Var $tmp.5) (Reg Rax))
             (Jmp (Label mult_conclusion)))))
         ((Label mult_start)
          (Block
            Binfo1
            ((Movq (Reg Rdi) (Var x.1))
             (Movq (Reg Rsi) (Var y.1))
             (Cmpq (Var x.1) (Imm 0))
             (JmpIf CC_e (Label block_1))
             (Jmp (Label block_2)))))))))))
