(X86Program
  (Info2
    (locals_types
      (($tmp.1 Integer)
       ($tmp.2 Integer)
       ($tmp.3 Integer)
       (x.1 Integer)))
    (conflicts
      (((VarL $tmp.1) ((RegL Rsp)))
       ((VarL $tmp.2) ((RegL Rsp)))
       ((VarL $tmp.3) ((RegL Rsp)))
       ((VarL x.1) ((RegL Rsp) (RegL Rflags)))
       ((RegL Rsp)
        ((VarL $tmp.1)
         (VarL $tmp.2)
         (VarL $tmp.3)
         (VarL x.1)
         (RegL Rax)
         (RegL Rcx)
         (RegL Rdx)
         (RegL Rsi)
         (RegL Rdi)
         (RegL R8)
         (RegL R9)
         (RegL R10)
         (RegL R11)
         (RegL Rflags)))
       ((RegL Rax)
        ((RegL Rsp)
         (RegL Rcx)
         (RegL Rdx)
         (RegL Rsi)
         (RegL Rdi)
         (RegL R8)
         (RegL R9)
         (RegL R10)
         (RegL R11)))
       ((RegL Rcx) ((RegL Rsp) (RegL Rax)))
       ((RegL Rdx) ((RegL Rsp) (RegL Rax)))
       ((RegL Rsi) ((RegL Rsp) (RegL Rax)))
       ((RegL Rdi) ((RegL Rsp) (RegL Rax)))
       ((RegL R8) ((RegL Rsp) (RegL Rax)))
       ((RegL R9) ((RegL Rsp) (RegL Rax)))
       ((RegL R10) ((RegL Rsp) (RegL Rax)))
       ((RegL R11) ((RegL Rsp) (RegL Rax)))
       ((RegL Rflags) ((VarL x.1) (RegL Rsp))))))
  (((Label block_1)
    (Block
      Binfo1
      ((Movq (Var x.1) (Var $tmp.2))
       (Movq (Var $tmp.2) (Var x.1))
       (Subq (Imm 2) (Var x.1))
       (Jmp (Label loop_1)))))
   ((Label block_2)
    (Block
      Binfo1
      ((Movq (Var x.1) (Var $tmp.3))
       (Movq (Var $tmp.3) (Reg Rax))
       (Addq (Imm 42) (Reg Rax))
       (Jmp (Label conclusion)))))
   ((Label loop_1)
    (Block
      Binfo1
      ((Movq (Var x.1) (Var $tmp.1))
       (Cmpq (Imm 0) (Var $tmp.1))
       (JmpIf CC_g (Label block_1))
       (Jmp (Label block_2)))))
   ((Label start)
    (Block
      Binfo1
      ((Callq (Label read_int) 0)
       (Movq (Reg Rax) (Var x.1))
       (Jmp (Label loop_1)))))))
