(X86Program
  (Info2
    (locals_types
      (($tmp.1 Integer)
       ($tmp.2 Integer)
       ($tmp.3 Integer)
       ($tmp.4 Integer)
       (x.1 Integer)
       (y.1 Integer)))
    (conflicts
      (((VarL $tmp.1)
        ((VarL $tmp.2)
         (VarL x.1)
         (VarL y.1)
         (RegL Rsp)
         (RegL Rax)
         (RegL Rcx)
         (RegL Rdx)
         (RegL Rsi)
         (RegL Rdi)
         (RegL R8)
         (RegL R9)
         (RegL R10)
         (RegL R11)))
       ((VarL $tmp.2)
        ((VarL $tmp.1)
         (VarL $tmp.3)
         (VarL x.1)
         (RegL Rsp)))
       ((VarL $tmp.3)
        ((VarL $tmp.2)
         (VarL $tmp.4)
         (VarL x.1)
         (RegL Rsp)))
       ((VarL $tmp.4)
        ((VarL $tmp.3) (RegL Rsp) (RegL Rax)))
       ((VarL x.1)
        ((VarL $tmp.1)
         (VarL $tmp.2)
         (VarL $tmp.3)
         (VarL y.1)
         (RegL Rsp)
         (RegL Rax)
         (RegL Rcx)
         (RegL Rdx)
         (RegL Rsi)
         (RegL Rdi)
         (RegL R8)
         (RegL R9)
         (RegL R10)
         (RegL R11)))
       ((VarL y.1)
        ((VarL $tmp.1)
         (VarL x.1)
         (RegL Rsp)
         (RegL Rax)
         (RegL Rcx)
         (RegL Rdx)
         (RegL Rsi)
         (RegL Rdi)
         (RegL R8)
         (RegL R9)
         (RegL R10)
         (RegL R11)))
       ((RegL Rsp)
        ((VarL $tmp.1)
         (VarL $tmp.2)
         (VarL $tmp.3)
         (VarL $tmp.4)
         (VarL x.1)
         (VarL y.1)
         (RegL Rax)
         (RegL Rcx)
         (RegL Rdx)
         (RegL Rsi)
         (RegL Rdi)
         (RegL R8)
         (RegL R9)
         (RegL R10)
         (RegL R11)))
       ((RegL Rax)
        ((VarL $tmp.1)
         (VarL $tmp.4)
         (VarL x.1)
         (VarL y.1)
         (RegL Rsp)
         (RegL Rcx)
         (RegL Rdx)
         (RegL Rsi)
         (RegL Rdi)
         (RegL R8)
         (RegL R9)
         (RegL R10)
         (RegL R11)))
       ((RegL Rcx)
        ((VarL $tmp.1)
         (VarL x.1)
         (VarL y.1)
         (RegL Rsp)
         (RegL Rax)))
       ((RegL Rdx)
        ((VarL $tmp.1)
         (VarL x.1)
         (VarL y.1)
         (RegL Rsp)
         (RegL Rax)))
       ((RegL Rsi)
        ((VarL $tmp.1)
         (VarL x.1)
         (VarL y.1)
         (RegL Rsp)
         (RegL Rax)))
       ((RegL Rdi)
        ((VarL $tmp.1)
         (VarL x.1)
         (VarL y.1)
         (RegL Rsp)
         (RegL Rax)))
       ((RegL R8)
        ((VarL $tmp.1)
         (VarL x.1)
         (VarL y.1)
         (RegL Rsp)
         (RegL Rax)))
       ((RegL R9)
        ((VarL $tmp.1)
         (VarL x.1)
         (VarL y.1)
         (RegL Rsp)
         (RegL Rax)))
       ((RegL R10)
        ((VarL $tmp.1)
         (VarL x.1)
         (VarL y.1)
         (RegL Rsp)
         (RegL Rax)))
       ((RegL R11)
        ((VarL $tmp.1)
         (VarL x.1)
         (VarL y.1)
         (RegL Rsp)
         (RegL Rax))))))
  (((Label start)
    (Block
      Binfo1
      ((Movq (Imm 10) (Var x.1))
       (Movq (Imm 0) (Var y.1))
       (Callq (Label read_int) 0)
       (Movq (Reg Rax) (Var y.1))
       (Movq (Var x.1) (Var $tmp.1))
       (Callq (Label read_int) 0)
       (Movq (Reg Rax) (Var x.1))
       (Movq (Var y.1) (Var $tmp.2))
       (Movq (Var $tmp.1) (Var $tmp.3))
       (Addq (Var $tmp.2) (Var $tmp.3))
       (Movq (Var x.1) (Var $tmp.4))
       (Movq (Var $tmp.3) (Reg Rax))
       (Addq (Var $tmp.4) (Reg Rax))
       (Jmp (Label conclusion)))))))
