(X86Program
  (Info2
    (locals_types
      (($tmp.1 Integer)
       ($tmp.10 Integer)
       ($tmp.2 Integer)
       ($tmp.3 Integer)
       ($tmp.4 Integer)
       ($tmp.5 Integer)
       ($tmp.6 Integer)
       ($tmp.7 Integer)
       ($tmp.8 Integer)
       ($tmp.9 Integer)
       (x.1 Integer)
       (y.1 Integer)))
    (conflicts
      (((VarL $tmp.1)
        ((VarL $tmp.2)
         (VarL y.1)
         (RegL Rsp)
         (RegL Rax)
         (RegL Rcx)
         (RegL Rdx)
         (RegL Rsi)
         (RegL Rdi)
         (RegL R8)
         (RegL R9)
         (RegL R10)
         (RegL R11)))
       ((VarL $tmp.10)
        ((VarL $tmp.7)
         (VarL $tmp.9)
         (RegL Rsp)
         (RegL Rax)))
       ((VarL $tmp.2)
        ((VarL $tmp.1)
         (VarL x.1)
         (VarL y.1)
         (RegL Rsp)))
       ((VarL $tmp.3)
        ((VarL $tmp.4)
         (VarL $tmp.5)
         (VarL $tmp.6)
         (VarL x.1)
         (VarL y.1)
         (RegL Rsp)
         (RegL Rax)
         (RegL Rcx)
         (RegL Rdx)
         (RegL Rsi)
         (RegL Rdi)
         (RegL R8)
         (RegL R9)
         (RegL R10)
         (RegL R11)))
       ((VarL $tmp.4)
        ((VarL $tmp.3)
         (VarL $tmp.5)
         (VarL x.1)
         (RegL Rsp)
         (RegL Rax)
         (RegL Rcx)
         (RegL Rdx)
         (RegL Rsi)
         (RegL Rdi)
         (RegL R8)
         (RegL R9)
         (RegL R10)
         (RegL R11)))
       ((VarL $tmp.5)
        ((VarL $tmp.3)
         (VarL $tmp.4)
         (VarL x.1)
         (VarL y.1)
         (RegL Rsp)))
       ((VarL $tmp.6)
        ((VarL $tmp.3)
         (VarL $tmp.7)
         (VarL x.1)
         (VarL y.1)
         (RegL Rsp)))
       ((VarL $tmp.7)
        ((VarL $tmp.10)
         (VarL $tmp.6)
         (VarL $tmp.8)
         (VarL $tmp.9)
         (VarL x.1)
         (VarL y.1)
         (RegL Rsp)))
       ((VarL $tmp.8)
        ((VarL $tmp.7)
         (VarL $tmp.9)
         (VarL y.1)
         (RegL Rsp)))
       ((VarL $tmp.9)
        ((VarL $tmp.10)
         (VarL $tmp.7)
         (VarL $tmp.8)
         (RegL Rsp)))
       ((VarL x.1)
        ((VarL $tmp.2)
         (VarL $tmp.3)
         (VarL $tmp.4)
         (VarL $tmp.5)
         (VarL $tmp.6)
         (VarL $tmp.7)
         (VarL y.1)
         (RegL Rsp)
         (RegL Rax)
         (RegL Rcx)
         (RegL Rdx)
         (RegL Rsi)
         (RegL Rdi)
         (RegL R8)
         (RegL R9)
         (RegL R10)
         (RegL R11)))
       ((VarL y.1)
        ((VarL $tmp.1)
         (VarL $tmp.2)
         (VarL $tmp.3)
         (VarL $tmp.5)
         (VarL $tmp.6)
         (VarL $tmp.7)
         (VarL $tmp.8)
         (VarL x.1)
         (RegL Rsp)
         (RegL Rax)
         (RegL Rcx)
         (RegL Rdx)
         (RegL Rsi)
         (RegL Rdi)
         (RegL R8)
         (RegL R9)
         (RegL R10)
         (RegL R11)))
       ((RegL Rsp)
        ((VarL $tmp.1)
         (VarL $tmp.10)
         (VarL $tmp.2)
         (VarL $tmp.3)
         (VarL $tmp.4)
         (VarL $tmp.5)
         (VarL $tmp.6)
         (VarL $tmp.7)
         (VarL $tmp.8)
         (VarL $tmp.9)
         (VarL x.1)
         (VarL y.1)
         (RegL Rax)
         (RegL Rcx)
         (RegL Rdx)
         (RegL Rsi)
         (RegL Rdi)
         (RegL R8)
         (RegL R9)
         (RegL R10)
         (RegL R11)))
       ((RegL Rax)
        ((VarL $tmp.1)
         (VarL $tmp.10)
         (VarL $tmp.3)
         (VarL $tmp.4)
         (VarL x.1)
         (VarL y.1)
         (RegL Rsp)
         (RegL Rcx)
         (RegL Rdx)
         (RegL Rsi)
         (RegL Rdi)
         (RegL R8)
         (RegL R9)
         (RegL R10)
         (RegL R11)))
       ((RegL Rcx)
        ((VarL $tmp.1)
         (VarL $tmp.3)
         (VarL $tmp.4)
         (VarL x.1)
         (VarL y.1)
         (RegL Rsp)
         (RegL Rax)))
       ((RegL Rdx)
        ((VarL $tmp.1)
         (VarL $tmp.3)
         (VarL $tmp.4)
         (VarL x.1)
         (VarL y.1)
         (RegL Rsp)
         (RegL Rax)))
       ((RegL Rsi)
        ((VarL $tmp.1)
         (VarL $tmp.3)
         (VarL $tmp.4)
         (VarL x.1)
         (VarL y.1)
         (RegL Rsp)
         (RegL Rax)))
       ((RegL Rdi)
        ((VarL $tmp.1)
         (VarL $tmp.3)
         (VarL $tmp.4)
         (VarL x.1)
         (VarL y.1)
         (RegL Rsp)
         (RegL Rax)))
       ((RegL R8)
        ((VarL $tmp.1)
         (VarL $tmp.3)
         (VarL $tmp.4)
         (VarL x.1)
         (VarL y.1)
         (RegL Rsp)
         (RegL Rax)))
       ((RegL R9)
        ((VarL $tmp.1)
         (VarL $tmp.3)
         (VarL $tmp.4)
         (VarL x.1)
         (VarL y.1)
         (RegL Rsp)
         (RegL Rax)))
       ((RegL R10)
        ((VarL $tmp.1)
         (VarL $tmp.3)
         (VarL $tmp.4)
         (VarL x.1)
         (VarL y.1)
         (RegL Rsp)
         (RegL Rax)))
       ((RegL R11)
        ((VarL $tmp.1)
         (VarL $tmp.3)
         (VarL $tmp.4)
         (VarL x.1)
         (VarL y.1)
         (RegL Rsp)
         (RegL Rax))))))
  (((Label start)
    (Block
      Binfo1
      ((Movq (Imm 30) (Var x.1))
       (Movq (Imm 20) (Var y.1))
       (Movq (Var x.1) (Var $tmp.1))
       (Callq (Label read_int) 0)
       (Movq (Reg Rax) (Var $tmp.2))
       (Movq (Var $tmp.1) (Var x.1))
       (Subq (Var $tmp.2) (Var x.1))
       (Movq (Imm 0) (Var $tmp.3))
       (Movq (Var y.1) (Var $tmp.4))
       (Callq (Label read_int) 0)
       (Movq (Reg Rax) (Var $tmp.5))
       (Movq (Var $tmp.4) (Var y.1))
       (Addq (Var $tmp.5) (Var y.1))
       (Movq (Imm 0) (Var $tmp.6))
       (Movq (Var $tmp.3) (Var $tmp.7))
       (Addq (Var $tmp.6) (Var $tmp.7))
       (Movq (Var x.1) (Var $tmp.8))
       (Movq (Var y.1) (Var $tmp.9))
       (Movq (Var $tmp.8) (Var $tmp.10))
       (Addq (Var $tmp.9) (Var $tmp.10))
       (Movq (Var $tmp.7) (Reg Rax))
       (Addq (Var $tmp.10) (Reg Rax))
       (Jmp (Label conclusion)))))))
