(X86Program
  (Info2
    (locals_types
      (($tmp.1 Integer)
       ($tmp.2 Integer)
       ($tmp.3 Integer)))
    (conflicts
      (((VarL $tmp.1) ((RegL Rsp)))
       ((VarL $tmp.2)
        ((VarL $tmp.3)
         (RegL Rsp)
         (RegL Rax)
         (RegL Rcx)
         (RegL Rdx)
         (RegL Rsi)
         (RegL Rdi)
         (RegL R8)
         (RegL R9)
         (RegL R10)
         (RegL R11)))
       ((VarL $tmp.3)
        ((VarL $tmp.2) (RegL Rsp) (RegL Rax)))
       ((RegL Rsp)
        ((VarL $tmp.1)
         (VarL $tmp.2)
         (VarL $tmp.3)
         (RegL Rax)
         (RegL Rcx)
         (RegL Rdx)
         (RegL Rsi)
         (RegL Rdi)
         (RegL R8)
         (RegL R9)
         (RegL R10)
         (RegL R11)))
       ((RegL Rax)
        ((VarL $tmp.2)
         (VarL $tmp.3)
         (RegL Rsp)
         (RegL Rcx)
         (RegL Rdx)
         (RegL Rsi)
         (RegL Rdi)
         (RegL R8)
         (RegL R9)
         (RegL R10)
         (RegL R11)))
       ((RegL Rcx)
        ((VarL $tmp.2) (RegL Rsp) (RegL Rax)))
       ((RegL Rdx)
        ((VarL $tmp.2) (RegL Rsp) (RegL Rax)))
       ((RegL Rsi)
        ((VarL $tmp.2) (RegL Rsp) (RegL Rax)))
       ((RegL Rdi)
        ((VarL $tmp.2) (RegL Rsp) (RegL Rax)))
       ((RegL R8)
        ((VarL $tmp.2) (RegL Rsp) (RegL Rax)))
       ((RegL R9)
        ((VarL $tmp.2) (RegL Rsp) (RegL Rax)))
       ((RegL R10)
        ((VarL $tmp.2) (RegL Rsp) (RegL Rax)))
       ((RegL R11)
        ((VarL $tmp.2) (RegL Rsp) (RegL Rax))))))
  (((Label start)
    (Block
      Binfo1
      ((Callq (Label read_int) 0)
       (Movq (Reg Rax) (Var $tmp.1))
       (Movq (Var $tmp.1) (Var $tmp.2))
       (Negq (Var $tmp.2))
       (Callq (Label read_int) 0)
       (Movq (Reg Rax) (Var $tmp.3))
       (Movq (Var $tmp.2) (Reg Rax))
       (Addq (Var $tmp.3) (Reg Rax))
       (Jmp (Label conclusion)))))))
