(X86Program
  (Info2
    (locals_types
      ((x1.1 Integer)
       (x2.1 Integer)
       (x3.1 Integer)
       (x4.1 Integer)
       (x5.1 Integer)
       (x6.1 Integer)
       ($tmp.1 Integer)
       ($tmp.2 Integer)
       ($tmp.3 Integer)
       ($tmp.4 Integer)
       ($tmp.5 Integer)
       ($tmp.6 Integer)
       ($tmp.7 Integer)
       ($tmp.8 Integer)
       ($tmp.9 Integer)))
    (conflicts
      (((VarL $tmp.1)
        ((VarL $tmp.2)
         (VarL x1.1)
         (VarL x3.1)
         (VarL x4.1)
         (VarL x5.1)
         (VarL x6.1)
         (RegL Rsp)))
       ((VarL $tmp.2)
        ((VarL $tmp.1)
         (VarL $tmp.3)
         (VarL $tmp.4)
         (VarL x3.1)
         (VarL x4.1)
         (VarL x5.1)
         (VarL x6.1)
         (RegL Rsp)))
       ((VarL $tmp.3)
        ((VarL $tmp.2)
         (VarL $tmp.4)
         (VarL x3.1)
         (VarL x5.1)
         (VarL x6.1)
         (RegL Rsp)))
       ((VarL $tmp.4)
        ((VarL $tmp.2)
         (VarL $tmp.3)
         (VarL $tmp.5)
         (VarL x5.1)
         (VarL x6.1)
         (RegL Rsp)))
       ((VarL $tmp.5)
        ((VarL $tmp.4)
         (VarL $tmp.6)
         (VarL $tmp.7)
         (VarL $tmp.8)
         (VarL x5.1)
         (VarL x6.1)
         (RegL Rsp)))
       ((VarL $tmp.6)
        ((VarL $tmp.5)
         (VarL $tmp.7)
         (VarL x5.1)
         (RegL Rsp)))
       ((VarL $tmp.7)
        ((VarL $tmp.5) (VarL $tmp.6) (RegL Rsp)))
       ((VarL $tmp.8)
        ((VarL $tmp.5) (VarL $tmp.9) (RegL Rsp)))
       ((VarL $tmp.9)
        ((VarL $tmp.8) (RegL Rsp)))
       ((VarL x1.1)
        ((VarL $tmp.1)
         (VarL x2.1)
         (VarL x3.1)
         (VarL x4.1)
         (VarL x5.1)
         (VarL x6.1)
         (RegL Rsp)
         (RegL Rax)
         (RegL Rcx)
         (RegL Rdx)
         (RegL Rsi)
         (RegL Rdi)
         (RegL R8)
         (RegL R9)
         (RegL R10)
         (RegL R11)))
       ((VarL x2.1)
        ((VarL x1.1)
         (VarL x3.1)
         (VarL x4.1)
         (VarL x5.1)
         (VarL x6.1)
         (RegL Rsp)
         (RegL Rax)
         (RegL Rcx)
         (RegL Rdx)
         (RegL Rsi)
         (RegL Rdi)
         (RegL R8)
         (RegL R9)
         (RegL R10)
         (RegL R11)))
       ((VarL x3.1)
        ((VarL $tmp.1)
         (VarL $tmp.2)
         (VarL $tmp.3)
         (VarL x1.1)
         (VarL x2.1)
         (VarL x4.1)
         (VarL x5.1)
         (VarL x6.1)
         (RegL Rsp)
         (RegL Rax)
         (RegL Rcx)
         (RegL Rdx)
         (RegL Rsi)
         (RegL Rdi)
         (RegL R8)
         (RegL R9)
         (RegL R10)
         (RegL R11)))
       ((VarL x4.1)
        ((VarL $tmp.1)
         (VarL $tmp.2)
         (VarL x1.1)
         (VarL x2.1)
         (VarL x3.1)
         (VarL x5.1)
         (VarL x6.1)
         (RegL Rsp)
         (RegL Rax)
         (RegL Rcx)
         (RegL Rdx)
         (RegL Rsi)
         (RegL Rdi)
         (RegL R8)
         (RegL R9)
         (RegL R10)
         (RegL R11)))
       ((VarL x5.1)
        ((VarL $tmp.1)
         (VarL $tmp.2)
         (VarL $tmp.3)
         (VarL $tmp.4)
         (VarL $tmp.5)
         (VarL $tmp.6)
         (VarL x1.1)
         (VarL x2.1)
         (VarL x3.1)
         (VarL x4.1)
         (VarL x6.1)
         (RegL Rsp)
         (RegL Rax)
         (RegL Rcx)
         (RegL Rdx)
         (RegL Rsi)
         (RegL Rdi)
         (RegL R8)
         (RegL R9)
         (RegL R10)
         (RegL R11)))
       ((VarL x6.1)
        ((VarL $tmp.1)
         (VarL $tmp.2)
         (VarL $tmp.3)
         (VarL $tmp.4)
         (VarL $tmp.5)
         (VarL x1.1)
         (VarL x2.1)
         (VarL x3.1)
         (VarL x4.1)
         (VarL x5.1)
         (RegL Rsp)))
       ((RegL Rsp)
        ((VarL $tmp.1)
         (VarL $tmp.2)
         (VarL $tmp.3)
         (VarL $tmp.4)
         (VarL $tmp.5)
         (VarL $tmp.6)
         (VarL $tmp.7)
         (VarL $tmp.8)
         (VarL $tmp.9)
         (VarL x1.1)
         (VarL x2.1)
         (VarL x3.1)
         (VarL x4.1)
         (VarL x5.1)
         (VarL x6.1)
         (RegL Rax)
         (RegL Rcx)
         (RegL Rdx)
         (RegL Rsi)
         (RegL Rdi)
         (RegL R8)
         (RegL R9)
         (RegL R10)
         (RegL R11)))
       ((RegL Rax)
        ((VarL x1.1)
         (VarL x2.1)
         (VarL x3.1)
         (VarL x4.1)
         (VarL x5.1)
         (RegL Rsp)
         (RegL Rcx)
         (RegL Rdx)
         (RegL Rsi)
         (RegL Rdi)
         (RegL R8)
         (RegL R9)
         (RegL R10)
         (RegL R11)))
       ((RegL Rcx)
        ((VarL x1.1)
         (VarL x2.1)
         (VarL x3.1)
         (VarL x4.1)
         (VarL x5.1)
         (RegL Rsp)
         (RegL Rax)))
       ((RegL Rdx)
        ((VarL x1.1)
         (VarL x2.1)
         (VarL x3.1)
         (VarL x4.1)
         (VarL x5.1)
         (RegL Rsp)
         (RegL Rax)))
       ((RegL Rsi)
        ((VarL x1.1)
         (VarL x2.1)
         (VarL x3.1)
         (VarL x4.1)
         (VarL x5.1)
         (RegL Rsp)
         (RegL Rax)))
       ((RegL Rdi)
        ((VarL x1.1)
         (VarL x2.1)
         (VarL x3.1)
         (VarL x4.1)
         (VarL x5.1)
         (RegL Rsp)
         (RegL Rax)))
       ((RegL R8)
        ((VarL x1.1)
         (VarL x2.1)
         (VarL x3.1)
         (VarL x4.1)
         (VarL x5.1)
         (RegL Rsp)
         (RegL Rax)))
       ((RegL R9)
        ((VarL x1.1)
         (VarL x2.1)
         (VarL x3.1)
         (VarL x4.1)
         (VarL x5.1)
         (RegL Rsp)
         (RegL Rax)))
       ((RegL R10)
        ((VarL x1.1)
         (VarL x2.1)
         (VarL x3.1)
         (VarL x4.1)
         (VarL x5.1)
         (RegL Rsp)
         (RegL Rax)))
       ((RegL R11)
        ((VarL x1.1)
         (VarL x2.1)
         (VarL x3.1)
         (VarL x4.1)
         (VarL x5.1)
         (RegL Rsp)
         (RegL Rax))))))
  (((Label start)
    (Block
      Binfo1
      ((Callq (Label read_int) 0)
       (Movq (Reg Rax) (Var x1.1))
       (Callq (Label read_int) 0)
       (Movq (Reg Rax) (Var x2.1))
       (Callq (Label read_int) 0)
       (Movq (Reg Rax) (Var x3.1))
       (Callq (Label read_int) 0)
       (Movq (Reg Rax) (Var x4.1))
       (Callq (Label read_int) 0)
       (Movq (Reg Rax) (Var x5.1))
       (Callq (Label read_int) 0)
       (Movq (Reg Rax) (Var x6.1))
       (Movq (Var x2.1) (Var $tmp.1))
       (Negq (Var $tmp.1))
       (Movq (Var x1.1) (Var $tmp.2))
       (Addq (Var $tmp.1) (Var $tmp.2))
       (Movq (Var x4.1) (Var $tmp.3))
       (Negq (Var $tmp.3))
       (Movq (Var x3.1) (Var $tmp.4))
       (Addq (Var $tmp.3) (Var $tmp.4))
       (Movq (Var $tmp.2) (Var $tmp.5))
       (Addq (Var $tmp.4) (Var $tmp.5))
       (Movq (Var x6.1) (Var $tmp.6))
       (Negq (Var $tmp.6))
       (Movq (Var x5.1) (Var $tmp.7))
       (Addq (Var $tmp.6) (Var $tmp.7))
       (Movq (Var $tmp.7) (Var $tmp.8))
       (Addq (Imm 0) (Var $tmp.8))
       (Movq (Var $tmp.5) (Var $tmp.9))
       (Addq (Var $tmp.8) (Var $tmp.9))
       (Movq (Var $tmp.9) (Reg Rax))
       (Addq (Imm 42) (Reg Rax))
       (Jmp (Label conclusion)))))))
