(X86Program
  (Info2
    (locals_types
      (($ea.1 (Vector (Integer)))
       ($tmp.1 Integer)
       ($tmp.2 Integer)
       ($tmp.3 Integer)
       ($tmp.4 Integer)
       ($tmp.5 Integer)
       (_.1 Unit)
       (_.2 Unit)
       (v.1 (Vector (Integer)))
       (x.1 Integer)))
    (conflicts
      (((VarL $ea.1)
        ((VarL _.1)
         (VarL x.1)
         (RegL Rsp)
         (RegL R11)))
       ((VarL $tmp.1) ((RegL Rsp) (RegL R15)))
       ((VarL $tmp.2)
        ((VarL x.1) (RegL Rsp) (RegL R15)))
       ((VarL $tmp.3)
        ((VarL $tmp.4)
         (VarL x.1)
         (RegL Rsp)
         (RegL R15)))
       ((VarL $tmp.4)
        ((VarL $tmp.3)
         (VarL x.1)
         (RegL Rsp)
         (RegL R15)))
       ((VarL $tmp.5) ((RegL Rsp)))
       ((VarL _.1) ((VarL $ea.1) (RegL Rsp)))
       ((VarL _.2) ((VarL x.1) (RegL Rsp)))
       ((VarL v.1) ((RegL Rsp)))
       ((VarL x.1)
        ((VarL $ea.1)
         (VarL $tmp.2)
         (VarL $tmp.3)
         (VarL $tmp.4)
         (VarL _.2)
         (RegL Rsp)
         (RegL Rax)
         (RegL Rcx)
         (RegL Rdx)
         (RegL Rsi)
         (RegL Rdi)
         (RegL R8)
         (RegL R9)
         (RegL R10)
         (RegL R11)
         (RegL R15)
         (RegL Rflags)))
       ((RegL Rsp)
        ((VarL $ea.1)
         (VarL $tmp.1)
         (VarL $tmp.2)
         (VarL $tmp.3)
         (VarL $tmp.4)
         (VarL $tmp.5)
         (VarL _.1)
         (VarL _.2)
         (VarL v.1)
         (VarL x.1)
         (RegL Rax)
         (RegL Rcx)
         (RegL Rdx)
         (RegL Rsi)
         (RegL Rdi)
         (RegL R8)
         (RegL R9)
         (RegL R10)
         (RegL R11)
         (RegL Rflags)))
       ((RegL Rax)
        ((VarL x.1)
         (RegL Rsp)
         (RegL Rcx)
         (RegL Rdx)
         (RegL Rsi)
         (RegL Rdi)
         (RegL R8)
         (RegL R9)
         (RegL R10)
         (RegL R11)
         (RegL R15)))
       ((RegL Rcx)
        ((VarL x.1)
         (RegL Rsp)
         (RegL Rax)
         (RegL R15)))
       ((RegL Rdx)
        ((VarL x.1)
         (RegL Rsp)
         (RegL Rax)
         (RegL R15)))
       ((RegL Rsi)
        ((VarL x.1)
         (RegL Rsp)
         (RegL Rax)
         (RegL Rdi)
         (RegL R15)))
       ((RegL Rdi)
        ((VarL x.1)
         (RegL Rsp)
         (RegL Rax)
         (RegL Rsi)
         (RegL R15)))
       ((RegL R8)
        ((VarL x.1)
         (RegL Rsp)
         (RegL Rax)
         (RegL R15)))
       ((RegL R9)
        ((VarL x.1)
         (RegL Rsp)
         (RegL Rax)
         (RegL R15)))
       ((RegL R10)
        ((VarL x.1)
         (RegL Rsp)
         (RegL Rax)
         (RegL R15)))
       ((RegL R11)
        ((VarL $ea.1)
         (VarL x.1)
         (RegL Rsp)
         (RegL Rax)
         (RegL R15)))
       ((RegL R15)
        ((VarL $tmp.1)
         (VarL $tmp.2)
         (VarL $tmp.3)
         (VarL $tmp.4)
         (VarL x.1)
         (RegL Rax)
         (RegL Rcx)
         (RegL Rdx)
         (RegL Rsi)
         (RegL Rdi)
         (RegL R8)
         (RegL R9)
         (RegL R10)
         (RegL R11)
         (RegL Rflags)))
       ((RegL Rflags)
        ((VarL x.1) (RegL Rsp) (RegL R15))))))
  (((Label block_1)
    (Block
      Binfo1
      ((Movq
         (GlobalArg (Label free_ptr))
         (Reg R11))
       (Addq
         (Imm 16)
         (GlobalArg (Label free_ptr)))
       (Movq (Imm 3) (Deref R11 0))
       (Movq (Reg R11) (Var $ea.1))
       (Movq (Var $ea.1) (Reg R11))
       (Movq (Var x.1) (Deref R11 8))
       (Movq (Imm 0) (Var _.1))
       (Movq (Var $ea.1) (Var v.1))
       (Movq (Var v.1) (Reg R11))
       (Movq (Deref R11 8) (Var $tmp.5))
       (Movq (Var $tmp.5) (Reg Rax))
       (Addq (Imm 1) (Reg Rax))
       (Jmp (Label conclusion)))))
   ((Label block_2)
    (Block
      Binfo1
      ((Movq (Imm 0) (Var _.2))
       (Jmp (Label block_1)))))
   ((Label block_3)
    (Block
      Binfo1
      ((Movq (Reg R15) (Reg Rdi))
       (Movq (Imm 16) (Reg Rsi))
       (Callq (Label collect) 2)
       (Jmp (Label block_1)))))
   ((Label block_4)
    (Block
      Binfo1
      ((Movq
         (GlobalArg (Label free_ptr))
         (Var $tmp.2))
       (Movq (Var $tmp.2) (Var $tmp.3))
       (Addq (Imm 16) (Var $tmp.3))
       (Movq
         (GlobalArg (Label fromspace_end))
         (Var $tmp.4))
       (Cmpq (Var $tmp.4) (Var $tmp.3))
       (JmpIf CC_l (Label block_2))
       (Jmp (Label block_3)))))
   ((Label block_5)
    (Block
      Binfo1
      ((Movq (Imm 41) (Var x.1))
       (Jmp (Label block_4)))))
   ((Label block_6)
    (Block
      Binfo1
      ((Movq (Imm 47) (Var x.1))
       (Jmp (Label block_4)))))
   ((Label start)
    (Block
      Binfo1
      ((Callq (Label read_int) 0)
       (Movq (Reg Rax) (Var $tmp.1))
       (Cmpq (Imm 1) (Var $tmp.1))
       (JmpIf CC_e (Label block_5))
       (Jmp (Label block_6)))))))
