(X86Program
  (Info2
    (locals_types
      (($ea.1 (Vector (Integer)))
       ($ea.2 (Vector (Integer)))
       ($ea.3 (Vector ((Vector (Integer)))))
       ($tmp.1 Integer)
       ($tmp.2 Integer)
       ($tmp.3 Integer)
       ($tmp.4 Integer)
       ($tmp.5 Integer)
       ($tmp.6 Integer)
       ($tmp.7 (Vector (Integer)))
       ($tmp.8 (Vector (Integer)))
       (_.1 Unit)
       (_.2 Unit)
       (_.3 Unit)
       (_.4 Unit)
       (v.1 (Vector ((Vector (Integer)))))
       (void.1 Unit)))
    (conflicts
      (((VarL $ea.1)
        ((VarL _.1)
         (RegL Rsp)
         (RegL R11)
         (RegL R15)))
       ((VarL $ea.2)
        ((VarL $ea.3)
         (VarL $tmp.4)
         (VarL $tmp.5)
         (VarL $tmp.6)
         (VarL _.4)
         (RegL Rsp)
         (RegL Rax)
         (RegL Rbx)
         (RegL Rcx)
         (RegL Rdx)
         (RegL Rsi)
         (RegL Rdi)
         (RegL R8)
         (RegL R9)
         (RegL R10)
         (RegL R11)
         (RegL R12)
         (RegL R13)
         (RegL R14)
         (RegL R15)
         (RegL Rflags)))
       ((VarL $ea.3)
        ((VarL $ea.2)
         (VarL _.3)
         (RegL Rsp)
         (RegL R11)))
       ((VarL $tmp.1) ((RegL Rsp) (RegL R15)))
       ((VarL $tmp.2)
        ((VarL $tmp.3) (RegL Rsp) (RegL R15)))
       ((VarL $tmp.3)
        ((VarL $tmp.2) (RegL Rsp) (RegL R15)))
       ((VarL $tmp.4)
        ((VarL $ea.2) (RegL Rsp) (RegL R15)))
       ((VarL $tmp.5)
        ((VarL $ea.2)
         (VarL $tmp.6)
         (RegL Rsp)
         (RegL R15)))
       ((VarL $tmp.6)
        ((VarL $ea.2)
         (VarL $tmp.5)
         (RegL Rsp)
         (RegL R15)))
       ((VarL $tmp.7) ((VarL v.1) (RegL Rsp)))
       ((VarL $tmp.8) ((RegL Rsp)))
       ((VarL _.1)
        ((VarL $ea.1) (RegL Rsp) (RegL R15)))
       ((VarL _.2) ((RegL Rsp) (RegL R15)))
       ((VarL _.3) ((VarL $ea.3) (RegL Rsp)))
       ((VarL _.4) ((VarL $ea.2) (RegL Rsp)))
       ((VarL v.1)
        ((VarL $tmp.7)
         (VarL void.1)
         (RegL Rsp)
         (RegL R11)))
       ((VarL void.1) ((VarL v.1) (RegL Rsp)))
       ((RegL Rsp)
        ((VarL $ea.1)
         (VarL $ea.2)
         (VarL $ea.3)
         (VarL $tmp.1)
         (VarL $tmp.2)
         (VarL $tmp.3)
         (VarL $tmp.4)
         (VarL $tmp.5)
         (VarL $tmp.6)
         (VarL $tmp.7)
         (VarL $tmp.8)
         (VarL _.1)
         (VarL _.2)
         (VarL _.3)
         (VarL _.4)
         (VarL v.1)
         (VarL void.1)
         (RegL Rax)
         (RegL Rcx)
         (RegL Rdx)
         (RegL Rsi)
         (RegL Rdi)
         (RegL R8)
         (RegL R9)
         (RegL R10)
         (RegL R11)
         (RegL Rflags)))
       ((RegL Rax)
        ((VarL $ea.2) (RegL Rsp) (RegL R15)))
       ((RegL Rbx) ((VarL $ea.2)))
       ((RegL Rcx)
        ((VarL $ea.2) (RegL Rsp) (RegL R15)))
       ((RegL Rdx)
        ((VarL $ea.2) (RegL Rsp) (RegL R15)))
       ((RegL Rsi)
        ((VarL $ea.2)
         (RegL Rsp)
         (RegL Rdi)
         (RegL R15)))
       ((RegL Rdi)
        ((VarL $ea.2)
         (RegL Rsp)
         (RegL Rsi)
         (RegL R15)))
       ((RegL R8)
        ((VarL $ea.2) (RegL Rsp) (RegL R15)))
       ((RegL R9)
        ((VarL $ea.2) (RegL Rsp) (RegL R15)))
       ((RegL R10)
        ((VarL $ea.2) (RegL Rsp) (RegL R15)))
       ((RegL R11)
        ((VarL $ea.1)
         (VarL $ea.2)
         (VarL $ea.3)
         (VarL v.1)
         (RegL Rsp)
         (RegL R15)))
       ((RegL R12) ((VarL $ea.2)))
       ((RegL R13) ((VarL $ea.2)))
       ((RegL R14) ((VarL $ea.2)))
       ((RegL R15)
        ((VarL $ea.1)
         (VarL $ea.2)
         (VarL $tmp.1)
         (VarL $tmp.2)
         (VarL $tmp.3)
         (VarL $tmp.4)
         (VarL $tmp.5)
         (VarL $tmp.6)
         (VarL _.1)
         (VarL _.2)
         (RegL Rax)
         (RegL Rcx)
         (RegL Rdx)
         (RegL Rsi)
         (RegL Rdi)
         (RegL R8)
         (RegL R9)
         (RegL R10)
         (RegL R11)
         (RegL Rflags)))
       ((RegL Rflags)
        ((VarL $ea.2) (RegL Rsp) (RegL R15))))))
  (((Label block_1)
    (Block
      Binfo1
      ((Movq
         (GlobalArg (Label free_ptr))
         (Reg R11))
       (Addq
         (Imm 16)
         (GlobalArg (Label free_ptr)))
       (Movq (Imm 131) (Deref R11 0))
       (Movq (Reg R11) (Var $ea.3))
       (Movq (Var $ea.3) (Reg R11))
       (Movq (Var $ea.2) (Deref R11 8))
       (Movq (Imm 0) (Var _.3))
       (Movq (Var $ea.3) (Var v.1))
       (Movq (Var v.1) (Reg R11))
       (Movq (Deref R11 8) (Var $tmp.7))
       (Movq (Var $tmp.7) (Reg R11))
       (Movq (Imm 42) (Deref R11 8))
       (Movq (Imm 0) (Var void.1))
       (Movq (Var v.1) (Reg R11))
       (Movq (Deref R11 8) (Var $tmp.8))
       (Movq (Var $tmp.8) (Reg R11))
       (Movq (Deref R11 8) (Reg Rax))
       (Jmp (Label conclusion)))))
   ((Label block_2)
    (Block
      Binfo1
      ((Movq (Imm 0) (Var _.4))
       (Jmp (Label block_1)))))
   ((Label block_3)
    (Block
      Binfo1
      ((Movq (Reg R15) (Reg Rdi))
       (Movq (Imm 16) (Reg Rsi))
       (Callq (Label collect) 2)
       (Jmp (Label block_1)))))
   ((Label block_4)
    (Block
      Binfo1
      ((Movq
         (GlobalArg (Label free_ptr))
         (Reg R11))
       (Addq
         (Imm 16)
         (GlobalArg (Label free_ptr)))
       (Movq (Imm 3) (Deref R11 0))
       (Movq (Reg R11) (Var $ea.1))
       (Movq (Var $ea.1) (Reg R11))
       (Movq (Imm 0) (Deref R11 8))
       (Movq (Imm 0) (Var _.1))
       (Movq (Var $ea.1) (Var $ea.2))
       (Movq
         (GlobalArg (Label free_ptr))
         (Var $tmp.4))
       (Movq (Var $tmp.4) (Var $tmp.5))
       (Addq (Imm 16) (Var $tmp.5))
       (Movq
         (GlobalArg (Label fromspace_end))
         (Var $tmp.6))
       (Cmpq (Var $tmp.6) (Var $tmp.5))
       (JmpIf CC_l (Label block_2))
       (Jmp (Label block_3)))))
   ((Label block_5)
    (Block
      Binfo1
      ((Movq (Imm 0) (Var _.2))
       (Jmp (Label block_4)))))
   ((Label block_6)
    (Block
      Binfo1
      ((Movq (Reg R15) (Reg Rdi))
       (Movq (Imm 16) (Reg Rsi))
       (Callq (Label collect) 2)
       (Jmp (Label block_4)))))
   ((Label start)
    (Block
      Binfo1
      ((Movq
         (GlobalArg (Label free_ptr))
         (Var $tmp.1))
       (Movq (Var $tmp.1) (Var $tmp.2))
       (Addq (Imm 16) (Var $tmp.2))
       (Movq
         (GlobalArg (Label fromspace_end))
         (Var $tmp.3))
       (Cmpq (Var $tmp.3) (Var $tmp.2))
       (JmpIf CC_l (Label block_5))
       (Jmp (Label block_6)))))))
