(X86Program
  (Info2
    (locals_types
      (($ea.1 (Vector (Integer Integer)))
       ($tmp.1 Integer)
       ($tmp.2 Integer)
       ($tmp.3 Integer)
       ($tmp.4 Integer)
       ($tmp.5 Integer)
       (_.1 Unit)
       (_.2 Unit)
       (_.3 Unit)
       (v.1 (Vector (Integer Integer)))))
    (conflicts
      (((VarL $ea.1)
        ((VarL _.1)
         (VarL _.2)
         (RegL Rsp)
         (RegL R11)))
       ((VarL $tmp.1) ((RegL Rsp) (RegL R15)))
       ((VarL $tmp.2)
        ((VarL $tmp.3) (RegL Rsp) (RegL R15)))
       ((VarL $tmp.3)
        ((VarL $tmp.2) (RegL Rsp) (RegL R15)))
       ((VarL $tmp.4)
        ((VarL $tmp.5)
         (VarL v.1)
         (RegL Rsp)
         (RegL R11)))
       ((VarL $tmp.5)
        ((VarL $tmp.4) (RegL Rsp) (RegL Rax)))
       ((VarL _.1)
        ((VarL $ea.1) (VarL v.1) (RegL Rsp)))
       ((VarL _.2)
        ((VarL $ea.1) (VarL v.1) (RegL Rsp)))
       ((VarL _.3) ((RegL Rsp)))
       ((VarL v.1)
        ((VarL $tmp.4)
         (VarL _.1)
         (VarL _.2)
         (RegL Rsp)
         (RegL R11)))
       ((RegL Rsp)
        ((VarL $ea.1)
         (VarL $tmp.1)
         (VarL $tmp.2)
         (VarL $tmp.3)
         (VarL $tmp.4)
         (VarL $tmp.5)
         (VarL _.1)
         (VarL _.2)
         (VarL _.3)
         (VarL v.1)
         (RegL Rax)
         (RegL Rcx)
         (RegL Rdx)
         (RegL Rsi)
         (RegL Rdi)
         (RegL R8)
         (RegL R9)
         (RegL R10)
         (RegL R11)
         (RegL Rflags)))
       ((RegL Rax) ((VarL $tmp.5) (RegL Rsp)))
       ((RegL Rcx) ((RegL Rsp)))
       ((RegL Rdx) ((RegL Rsp)))
       ((RegL Rsi) ((RegL Rsp) (RegL Rdi)))
       ((RegL Rdi) ((RegL Rsp) (RegL Rsi)))
       ((RegL R8) ((RegL Rsp)))
       ((RegL R9) ((RegL Rsp)))
       ((RegL R10) ((RegL Rsp)))
       ((RegL R11)
        ((VarL $ea.1)
         (VarL $tmp.4)
         (VarL v.1)
         (RegL Rsp)))
       ((RegL R15)
        ((VarL $tmp.1)
         (VarL $tmp.2)
         (VarL $tmp.3)
         (RegL Rflags)))
       ((RegL Rflags) ((RegL Rsp) (RegL R15))))))
  (((Label block_1)
    (Block
      Binfo1
      ((Movq
         (GlobalArg (Label free_ptr))
         (Reg R11))
       (Addq
         (Imm 24)
         (GlobalArg (Label free_ptr)))
       (Movq (Imm 5) (Deref R11 0))
       (Movq (Reg R11) (Var $ea.1))
       (Movq (Var $ea.1) (Reg R11))
       (Movq (Imm 0) (Deref R11 8))
       (Movq (Imm 0) (Var _.2))
       (Movq (Var $ea.1) (Reg R11))
       (Movq (Imm 0) (Deref R11 16))
       (Movq (Imm 0) (Var _.1))
       (Movq (Var $ea.1) (Var v.1))
       (Movq (Var v.1) (Reg R11))
       (Movq (Imm 38) (Deref R11 8))
       (Movq (Imm 0) (Var _.1))
       (Movq (Var v.1) (Reg R11))
       (Movq (Imm 4) (Deref R11 16))
       (Movq (Imm 0) (Var _.2))
       (Movq (Var v.1) (Reg R11))
       (Movq (Deref R11 8) (Var $tmp.4))
       (Movq (Var v.1) (Reg R11))
       (Movq (Deref R11 16) (Var $tmp.5))
       (Movq (Var $tmp.4) (Reg Rax))
       (Addq (Var $tmp.5) (Reg Rax))
       (Jmp (Label conclusion)))))
   ((Label block_2)
    (Block
      Binfo1
      ((Movq (Imm 0) (Var _.3))
       (Jmp (Label block_1)))))
   ((Label block_3)
    (Block
      Binfo1
      ((Movq (Reg R15) (Reg Rdi))
       (Movq (Imm 24) (Reg Rsi))
       (Callq (Label collect) 2)
       (Jmp (Label block_1)))))
   ((Label start)
    (Block
      Binfo1
      ((Movq
         (GlobalArg (Label free_ptr))
         (Var $tmp.1))
       (Movq (Var $tmp.1) (Var $tmp.2))
       (Addq (Imm 24) (Var $tmp.2))
       (Movq
         (GlobalArg (Label fromspace_end))
         (Var $tmp.3))
       (Cmpq (Var $tmp.3) (Var $tmp.2))
       (JmpIf CC_l (Label block_2))
       (Jmp (Label block_3)))))))
