(X86Program
  (Info2
    (locals_types
      (($ea.1 (Vector (Integer)))
       ($ea.2 (Vector (Integer)))
       ($tmp.1 Integer)
       ($tmp.2 Integer)
       ($tmp.3 Integer)
       ($tmp.4 Integer)
       ($tmp.5 Integer)
       ($tmp.6 Integer)
       (_.1 Unit)
       (_.2 Unit)
       (_.3 Unit)
       (_.4 Unit)
       (v1.1 (Vector (Integer)))
       (v2.1 (Vector (Integer)))))
    (conflicts
      (((VarL $ea.1)
        ((VarL _.1)
         (RegL Rsp)
         (RegL R11)
         (RegL R15)))
       ((VarL $ea.2)
        ((VarL _.3)
         (VarL v1.1)
         (RegL Rsp)
         (RegL R11)))
       ((VarL $tmp.1) ((RegL Rsp) (RegL R15)))
       ((VarL $tmp.2)
        ((VarL $tmp.3) (RegL Rsp) (RegL R15)))
       ((VarL $tmp.3)
        ((VarL $tmp.2) (RegL Rsp) (RegL R15)))
       ((VarL $tmp.4)
        ((VarL v1.1) (RegL Rsp) (RegL R15)))
       ((VarL $tmp.5)
        ((VarL $tmp.6)
         (VarL v1.1)
         (RegL Rsp)
         (RegL R15)))
       ((VarL $tmp.6)
        ((VarL $tmp.5)
         (VarL v1.1)
         (RegL Rsp)
         (RegL R15)))
       ((VarL _.1)
        ((VarL $ea.1) (RegL Rsp) (RegL R15)))
       ((VarL _.2) ((RegL Rsp) (RegL R15)))
       ((VarL _.3)
        ((VarL $ea.2) (VarL v1.1) (RegL Rsp)))
       ((VarL _.4) ((VarL v1.1) (RegL Rsp)))
       ((VarL v1.1)
        ((VarL $ea.2)
         (VarL $tmp.4)
         (VarL $tmp.5)
         (VarL $tmp.6)
         (VarL _.3)
         (VarL _.4)
         (VarL v2.1)
         (RegL Rsp)
         (RegL Rax)
         (RegL Rbx)
         (RegL Rcx)
         (RegL Rdx)
         (RegL Rsi)
         (RegL Rdi)
         (RegL R8)
         (RegL R9)
         (RegL R10)
         (RegL R11)
         (RegL R12)
         (RegL R13)
         (RegL R14)
         (RegL R15)
         (RegL Rflags)))
       ((VarL v2.1) ((VarL v1.1) (RegL Rsp)))
       ((RegL Rsp)
        ((VarL $ea.1)
         (VarL $ea.2)
         (VarL $tmp.1)
         (VarL $tmp.2)
         (VarL $tmp.3)
         (VarL $tmp.4)
         (VarL $tmp.5)
         (VarL $tmp.6)
         (VarL _.1)
         (VarL _.2)
         (VarL _.3)
         (VarL _.4)
         (VarL v1.1)
         (VarL v2.1)
         (RegL Rax)
         (RegL Rcx)
         (RegL Rdx)
         (RegL Rsi)
         (RegL Rdi)
         (RegL R8)
         (RegL R9)
         (RegL R10)
         (RegL R11)
         (RegL Rflags)))
       ((RegL Rax)
        ((VarL v1.1) (RegL Rsp) (RegL R15)))
       ((RegL Rbx) ((VarL v1.1)))
       ((RegL Rcx)
        ((VarL v1.1) (RegL Rsp) (RegL R15)))
       ((RegL Rdx)
        ((VarL v1.1) (RegL Rsp) (RegL R15)))
       ((RegL Rsi)
        ((VarL v1.1)
         (RegL Rsp)
         (RegL Rdi)
         (RegL R15)))
       ((RegL Rdi)
        ((VarL v1.1)
         (RegL Rsp)
         (RegL Rsi)
         (RegL R15)))
       ((RegL R8)
        ((VarL v1.1) (RegL Rsp) (RegL R15)))
       ((RegL R9)
        ((VarL v1.1) (RegL Rsp) (RegL R15)))
       ((RegL R10)
        ((VarL v1.1) (RegL Rsp) (RegL R15)))
       ((RegL R11)
        ((VarL $ea.1)
         (VarL $ea.2)
         (VarL v1.1)
         (RegL Rsp)
         (RegL R15)))
       ((RegL R12) ((VarL v1.1)))
       ((RegL R13) ((VarL v1.1)))
       ((RegL R14) ((VarL v1.1)))
       ((RegL R15)
        ((VarL $ea.1)
         (VarL $tmp.1)
         (VarL $tmp.2)
         (VarL $tmp.3)
         (VarL $tmp.4)
         (VarL $tmp.5)
         (VarL $tmp.6)
         (VarL _.1)
         (VarL _.2)
         (VarL v1.1)
         (RegL Rax)
         (RegL Rcx)
         (RegL Rdx)
         (RegL Rsi)
         (RegL Rdi)
         (RegL R8)
         (RegL R9)
         (RegL R10)
         (RegL R11)
         (RegL Rflags)))
       ((RegL Rflags)
        ((VarL v1.1) (RegL Rsp) (RegL R15))))))
  (((Label block_1)
    (Block
      Binfo1
      ((Movq (Imm 777) (Reg Rax))
       (Jmp (Label conclusion)))))
   ((Label block_2)
    (Block
      Binfo1
      ((Movq (Imm 42) (Reg Rax))
       (Jmp (Label conclusion)))))
   ((Label block_3)
    (Block
      Binfo1
      ((Movq
         (GlobalArg (Label free_ptr))
         (Reg R11))
       (Addq
         (Imm 16)
         (GlobalArg (Label free_ptr)))
       (Movq (Imm 3) (Deref R11 0))
       (Movq (Reg R11) (Var $ea.2))
       (Movq (Var $ea.2) (Reg R11))
       (Movq (Imm 0) (Deref R11 8))
       (Movq (Imm 0) (Var _.3))
       (Movq (Var $ea.2) (Var v2.1))
       (Cmpq (Var v2.1) (Var v1.1))
       (JmpIf CC_e (Label block_1))
       (Jmp (Label block_2)))))
   ((Label block_4)
    (Block
      Binfo1
      ((Movq (Imm 0) (Var _.4))
       (Jmp (Label block_3)))))
   ((Label block_5)
    (Block
      Binfo1
      ((Movq (Reg R15) (Reg Rdi))
       (Movq (Imm 16) (Reg Rsi))
       (Callq (Label collect) 2)
       (Jmp (Label block_3)))))
   ((Label block_6)
    (Block
      Binfo1
      ((Movq
         (GlobalArg (Label free_ptr))
         (Reg R11))
       (Addq
         (Imm 16)
         (GlobalArg (Label free_ptr)))
       (Movq (Imm 3) (Deref R11 0))
       (Movq (Reg R11) (Var $ea.1))
       (Movq (Var $ea.1) (Reg R11))
       (Movq (Imm 0) (Deref R11 8))
       (Movq (Imm 0) (Var _.1))
       (Movq (Var $ea.1) (Var v1.1))
       (Movq
         (GlobalArg (Label free_ptr))
         (Var $tmp.4))
       (Movq (Var $tmp.4) (Var $tmp.5))
       (Addq (Imm 16) (Var $tmp.5))
       (Movq
         (GlobalArg (Label fromspace_end))
         (Var $tmp.6))
       (Cmpq (Var $tmp.6) (Var $tmp.5))
       (JmpIf CC_l (Label block_4))
       (Jmp (Label block_5)))))
   ((Label block_7)
    (Block
      Binfo1
      ((Movq (Imm 0) (Var _.2))
       (Jmp (Label block_6)))))
   ((Label block_8)
    (Block
      Binfo1
      ((Movq (Reg R15) (Reg Rdi))
       (Movq (Imm 16) (Reg Rsi))
       (Callq (Label collect) 2)
       (Jmp (Label block_6)))))
   ((Label start)
    (Block
      Binfo1
      ((Movq
         (GlobalArg (Label free_ptr))
         (Var $tmp.1))
       (Movq (Var $tmp.1) (Var $tmp.2))
       (Addq (Imm 16) (Var $tmp.2))
       (Movq
         (GlobalArg (Label fromspace_end))
         (Var $tmp.3))
       (Cmpq (Var $tmp.3) (Var $tmp.2))
       (JmpIf CC_l (Label block_7))
       (Jmp (Label block_8)))))))
